### ISSUE TITLE
Config location 

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado-vt#100]
Avocado taken from git ignores system-wide configs:

/etc/avocado....
as well as it ignores configs at ~/

./scripts/avocado config --datadir
Config files read (in order):
    /mnt/tests/spice/qe-tests/avocado/etc/avocado/avocado.conf
    /mnt/tests/spice/qe-tests/avocado/etc/avocado/conf.d/gdb.conf
    /mnt/tests/spice/qe-tests/avocado/etc/avocado/conf.d/vt.conf

This contradicts with:

http://avocado-framework.readthedocs.org/en/latest/Configuration.html#parsing-order-recap

**Comment by lmr** [comment]
I'll fix the documentation.

**Comment by lmr** [comment]
BTW, this should've been opened in the avocado repo, instead of avocado-vt. Anyway, I've created https://github.com/avocado-framework/avocado/pull/778 to fix the documentation lack of mention of the special case.

**Comment by lmr** [comment]
I'm closing this now that https://github.com/avocado-framework/avocado/pull/778 was merged.
