### ISSUE TITLE
Any plans to support running avocado(misc) tests through avocado-vt?

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado-vt#1068]
Any plans to support running avocaod(misc) tests through avocado-vt similar to autotest-client-tests:

Reference:
`def run_autotest(vm, session, control_path, timeout,
                 outputdir, params, copy_only=False, control_args=None,
                 ignore_session_terminated=False):
`

`virttest/utils_test/__init__.py
`
If then would like to contribute aswell :-)

**Comment by sathnaga** [comment]
@ldoktor @lmr @adereis @clebergnu

**Comment by lmr** [comment]
@sathnaga I don't know about the plans, although that doesn't seem particularly difficult to implement in a cleaner fashion with avocado. It all boils down to time allocation and resources, and the perception that such a mechanism will be useful enough.

**Comment by adereis** [comment]
On Tue, Jul 18, 2017 at 07:18:59AM -0700, Satheesh Rajendran wrote:
> @ldoktor @lmr @adereis @clebergnu 
> 

Please don't do that. Someone will look at your question at some
point. Referring everyone just to draw attention to your issue is
not a good practice, unless it's something urgent or if you've been
waiting for too long (not the case here).

Thanks.

**Comment by sathnaga** [comment]
@adereis Just tagged you guys to get your opinion, not to draw quick attention though.
Sorry if it bothered you, won't repeat in future:-)

**Comment by ldoktor** [comment]
It should actually be way simpler than `autest-misc-tests` and I'd definitely promote the use sparse checkout for getting files and datadirs... it'd speed up things significantly.

Anyway feel free to send patches, they'd be gladly welcomed.

**Comment by sathnaga** [comment]
Have sent a RFC patch, please let me know your views on the approach, will work refining it as required,
https://github.com/avocado-framework/avocado-vt/pull/1094
https://github.com/autotest/tp-qemu/pull/1036

**Comment by sathnaga** [comment]
Framework patch is merged, closing this issue
