### ISSUE TITLE
'module' object has no attribute 'verify_dmesg'

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/avocado-vt#1168]
https://github.com/avocado-framework/avocado-vt/pull/1078 introduced an issue:
```
16:23:29 ERROR| Reproduced traceback from: /home/staf-test/workspace/avocado/avocado/core/test.py:630
16:23:29 ERROR| Traceback (most recent call last):
16:23:29 ERROR|   File "/home/staf-test/workspace/avocado-vt/avocado_vt/test.py", line 271, in runTest
16:23:29 ERROR|     raise self.__status  # pylint: disable=E0702
16:23:29 ERROR| AttributeError: 'module' object has no attribute 'verify_dmesg'
```
And the job would stuck at the end until test timeout expired. Need to fix it asap.

**Comment by sathnaga** [comment]
@luckyh looking right now

**Comment by sathnaga** [comment]
@luckyh moved verify_dmesg under VM class in dependency PR and missed the change here, found a fix, testing it, will post in a while , sorry for the inconvenience, thanks for reporting :-)

**Comment by sathnaga** [comment]
@luckyh can you please review and merge it, thanks in advance.
