### ISSUE TITLE
RFC: making vm session as test object ?

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado-vt#1184]
Just an thought, how about making vm session as a per test object so that
by default(test with startvm=yes) will hold this object, and any one can directly use the session, will attach to the available console object rather than fresh login and create a new session object, it can be tried for renew incase of object destroy(incase of reboot, shutdown, error) during test as next invocation of session, or `magically` automatic by hooks in vm reboot, start methods.

Why needed, 
1. we can get a continued logs per test for all actions inside guest.
2. saves time.
3. easy usage.

**Comment by pevogam** [comment]
We have many test objects with an OS that might not necessarily support a vm session of any type. An immediate example is use cases where the tests only operate through the GUI at the VNC port of the virtual machine. Adding this extra assumption for all test objects will therefore break things for us.

**Comment by sathnaga** [comment]
okies, got it..

**Comment by sathnaga** [comment]
Closing as it will have issues for some environment.
