### ISSUE TITLE
Avocado exits when avocado-vt fails to create list of tests

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado-vt#12]
Hello @lmr, I have another problem with avocado-vt and I think we might reconsider the logic. I'm getting:

Guest name JeOS.19 is not on the known guest os list (see --vt-list-guests), aborting...

Which is fine, because I'm running `passtest`. I don't care that avocado-vt is unable to get jobs in this run and I supply different image when I need it.

What do you think about only adding warning: plugin avocado-vt failed to list tests, disabling `avocado-vt` and proceed with another plugin? I think that would be desirable.

Regards,
Lukáš

**Comment by lmr** [comment]
@ldoktor Let me know if this is still an issue when you can.

**Comment by ldoktor** [comment]
Hi @lmr, the change worked only partially. For example wrong nettype still prevents `passtest` from being executed. The https://github.com/avocado-framework/avocado-vt/issues/20 should hopefully fix all problems.

**Comment by lmr** [comment]
Closing this, since #21 fixes the problem.
