### ISSUE TITLE
RFE: allow extending extra_params from loader

### ISSUE THREAD

**Issue by wainersm** [avocado-framework/avocado-vt#1346]
The mux to loader plug-in provides the "test_reference_resolver_extra" which is actually not handled by avocado-vt's loader. I'd like to use test_reference_resolver_extra to pass extra parameters (e.g. "nettype=bridge") to test execution.

@ldoktor has already a patch for this.

**Comment by ldoktor** [comment]
Well you didn't have to create an issue for that, simply saying it's useful would suffice, anyway here you go: https://github.com/avocado-framework/avocado-vt/pull/1347

**Comment by wainersm** [comment]
Sorry @ldoktor , I thought I had to fill an enhancement request just for the sake of record.
I've just reviewed and approved your patch. Thanks!

**Comment by wainersm** [comment]
PR #1347 implemented this feature. Closing the issue...
