### ISSUE TITLE
README.rst "Getting Started" suggestions

### ISSUE THREAD

**Issue by ehabkost** [avocado-framework/avocado-vt#136]
I had some issues when following the "Getting Started" guide from README.rst to setup avocado-vt:

* When I hit issue #126, I didn't know there was a `~/avocado` directory. Maybe the section that says that vt-bootstrap "will generate [...] symlinks in your avocado source code dir" should also mention that `~/avocado` will be created.
* The `avocado.core.plugins.vt` plugin was not being loaded, with the following error: `ImportError No module named autotest.client.shared`. It could be fixed by setting `$AUTOTEST_PATH`, but the Getting Started guide doesn't even mention that avocado-vt has dependencies on autotest, and how to set it up.

I believe the Getting Started guide could be clarified to avoid these issues.

I am not submitting a patch myself because I am not sure when exactly the `~/avocado` directory is created, and how to properly document autotest dependencies.

**Comment by lmr** [comment]
Sure, thanks!

**Comment by lmr** [comment]
This has been addressed in #164

**Comment by lmr** [comment]
Closing due to #164 merge.
