### ISSUE TITLE
avocado-vt doesn't load changes made on test provider config files

### ISSUE THREAD

**Issue by ehabkost** [avocado-framework/avocado-vt#139]
With virt-test:

    $ ./run -t qemu --list-tests | grep Nehalem | grep pc_1_0
    438 type_specific.io-github-autotest-qemu.qemu_cpu.cpuid.full_dump.default.default.machine_type_upstream.pc_1_0.kvm.cpu_model_intel.Nehalem.host_cpu_vendor_unknown.qemu_flavor_unknown
    $ sed -i 's/default:/defaultxxx:/' test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/cfg/qemu_cpu.cfg 
    $ ./run -t qemu --list-tests | grep Nehalem | grep pc_1_0
    438 type_specific.io-github-autotest-qemu.qemu_cpu.cpuid.full_dump.defaultxxx.defaultxxx.machine_type_upstream.pc_1_0.kvm.cpu_model_intel.Nehalem.host_cpu_vendor_unknown.qemu_flavor_unknown
    $ 

With avocado-vt:

    $ ./scripts/avocado list Nehalem..pc_1_0
    VT type_specific.io-github-autotest-qemu.qemu_cpu.cpuid.full_dump.default.default.machine_type_upstream.pc_1_0.kvm.cpu_model_intel.Nehalem.host_cpu_vendor_unknown.qemu_fl
    $ sed -i 's/default:/defaultxxx:/' ~/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/cfg/qemu_cpu.cfg
    $ ./scripts/avocado list Nehalem..pc_1_0
    VT type_specific.io-github-autotest-qemu.qemu_cpu.cpuid.full_dump.default.default.machine_type_upstream.pc_1_0.kvm.cpu_model_intel.Nehalem.host_cpu_vendor_unknown.qemu_fl
    $ 

It looks like subtests.cfg is not being recreated when necessary.

**Comment by lmr** [comment]
This has been addressed in PR #164.

**Comment by lmr** [comment]
Closing with #164
