### ISSUE TITLE
Feuture req: path to windows ISOs should have same prefix

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado-vt#156]
Most Windows ISO images prefix is: isos/windows

Example:
grep -rn cdrom_cd1 shared/cfg/guest-os/Windows

shared/cfg/guest-os/Windows/Win2000/i386.cfg:4:        cdrom_cd1 = isos/windows/Windows2000_sp4.iso

Only next 3 isos have strange prefix:

grep -rnE 'cdrom_cd1.*ISO' shared/cfg/guest-os/Windows
shared/cfg/guest-os/Windows/Win8/x86_64.cfg:43:                cdrom_cd1 = isos/ISO/Win8.1/en_windows_8_1_enterprise_x64_dvd_2971902.iso
shared/cfg/guest-os/Windows/Win8/i386.cfg:35:                cdrom_cd1 = isos/ISO/Win8.1/en_windows_8_1_enterprise_x86_dvd_2972289.iso
shared/cfg/guest-os/Windows/Win2012/x86_64.cfg:29:                cdrom_cd1 = isos/ISO/Win2012R2/en_windows_server_2012_r2_x64_dvd_2707946.iso

Could you please change this three also to isos/windows ?
It would be fine to have all ISOs at same dir. Thanks.

**Comment by lmr** [comment]
I'm assuming the person who contributed the original patch adding those Windows versions has a particular internal organization of their ISO files. I'd say it's OK to send a PR to change it, but it'd be polite to notify the original author of the lines (that can be looked up with `git blame`) saying that your patch is changing it.

**Comment by lmr** [comment]
I'm closing this, as the problem mentioned was already solved in https://github.com/avocado-framework/avocado-vt/commit/df81b4c480ae4fda0371eb14f341b4c76807162c
