### ISSUE TITLE
vt-boostrap asks me twice if I want to download JeOS 19 x86_64

### ISSUE THREAD

**Issue by ehabkost** [avocado-framework/avocado-vt#172]
vt-bootstrap seems to be asking me the same question twice (just with different wording):

    11:50:50 INFO | 6 - Verifying (and possibly downloading) guest image
    File JeOS 19 x86_64 not present. Do you want to download it? (y/n) y
    11:50:52 INFO | Verifying expected SHA1 sum from http://lmr.fedorapeople.org/jeos/SHA1SUM_JEOS19
    11:50:52 INFO | Expected SHA1 sum: f5141c3f9d51ee340660f2b96b2b842ceab9128f
    11:50:52 WARNI| File /usr/share/avocado/data/avocado-vt/images/jeos-19-64.qcow2.7z not found
    Would you like to download it from http://lmr.fedorapeople.org/jeos/jeos-19-64.qcow2.7z? (y/n) y

**Comment by lmr** [comment]
Oh yeah, this has been there pretty much forever. I agree that it's necessary to cut one of the questions.
