### ISSUE TITLE
s390x: Error 'Symlink /dev/vport0p0 does not exist' when executing test virtio_console.spread_2.specifiable.virtconsole.virtio_console_smoke.check_zero_sym

### ISSUE THREAD

**Issue by KarMez-Redhat** [avocado-framework/avocado-vt#1736]
Version-Release number of selected component (if applicable):
   s390x
   Red Hat Enterprise Linux Server release 7.6 Beta (Maipo)
   qemu-kvm-ma-2.12.0-7.el7.s390x
   kernel-4.14.0-87.el7a.s390x
   Avocado 63.0

The following error occurs when executing the avocado test type_specific.io-github-autotest-qemu.virtio_console.spread_2.specifiable.virtconsole.virtio_console_smoke.check_zero_sym on s390x:

     -> VirtioPortException: Failed to execute 'virt.check_zero_sym()' on virtio_console_guest.py, vm: avocado-vt-vm1, output:
     -> FAIL: Symlink /dev/vport0p0 does not exist.

Initially, this issue appeared to be a qemu-kvm issue but after some research by Cornelia Huck and Thomas Huth, the general consensus is that this may be an Avocado test issue.

All relevant information concerning this issue can be found in this BZ, including Steps to Reproduce, log files and comments: https://bugzilla.redhat.com/show_bug.cgi?id=1621917

I have not seen this issue occur on x86_64, ppc64le or aarch64 in recent testing. So my concern is that this seems to be a s390x-related issue.

**Comment by ldoktor** [comment]
I'm able to reproduce it on x86_64. Basically we used a wrong assumption that 0p0 always has to be there. As it's not true this whole variant doesn't makes sense and there is already the check for the number of `vport\d+p\d+` devices, which should catch missing symlinks so let's just remove this test.
