### ISSUE TITLE
arm64-pci does not support device hotplug

### ISSUE THREAD

**Issue by rayx** [avocado-framework/avocado-vt#1847]
Test generates the following qemu command line after I add "pcie_extra_root_port = 3" to 
arm64-pci section:

<pre><code>
    -device pcie-root-port,id=pcie_root_port_0,bus=pcie.0,addr=0x1 \
    -device pcie-root-port,id=pcie_root_port_1,bus=pcie.0,addr=0x2 \
    -device pcie-root-port,id=pcie_root_port_2,bus=pcie.0,addr=0x3  \
</code></pre>

This causes qemu fails to start because "chassis" option is required.

**Comment by rayx** [comment]
Forgot to mention, I tried to debug the issue by putting a break point at QPCIEBus.add_root_port() but it wasn't hit. Can anyone please suggest which part of the code I should look at?

**Comment by vivianQizhu** [comment]
@rayx https://github.com/avocado-framework/avocado-vt/blob/master/virttest/qemu_devices/qcontainer.py#L801 here, only q35 use QPCIEBus, arm use QPCIBus, seems arm is far away from support hotplug...

**Comment by vivianQizhu** [comment]
@rayx You are welcome, and I recommend modify the issue title to something like "arm64-pci does not support device hotplug", "chassis" option is only part of this issue.

**Comment by rayx** [comment]
The issue blocks all tests on aarch64 that use pcie root port. There are a lot of tests doing so: *_hotplug, migrate, etc.

**Comment by rayx** [comment]
Since it blocks a large number of tests, I fix it at https://github.com/avocado-framework/avocado-vt/pull/1879. Not sure if it will be accepted, but the patch works for me and I can continue running the rest tests.

**Comment by rayx** [comment]
This is fixed in https://github.com/avocado-framework/avocado-vt/pull/1879
