### ISSUE TITLE
avocado-vt spec file

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#1890]
Is it intentional that the spec file in the current repo does not support releases (only snapshot versions tracked by commit hashes) and dual python2-python3 package generation (i.e. python3 support) in comparison to repos like aexpect and the main avocado repo? If it is simply not developed, I might contribute an updated spec file but I wanted to know if I am missing something as smaller repos like aexpect have extended spec file with both of these.

**Comment by clebergnu** [comment]
These all look like shortcomings that could be improved. Please go ahead
and contribute the changes. Thanks!

**Comment by pevogam** [comment]
Closing since #1891 was already merged.
