### ISSUE TITLE
Only old PyPI version available

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#1964]
It seems that the `pip` downloadable version of the plugin is fairly old by now:

    $ pip search avocado
    avocado-framework (68.0)                               - Avocado Test Framework
    avocado-framework-plugin-vt (57.4)                     - Avocado Plugin for Virtualization Testing
    avocado-framework-plugin-golang (68.0)                 - Avocado Plugin for Execution of Golang tests
    avocado-framework-plugin-robot (68.0)                  - Avocado Plugin for Execution of Robot Framework tests
    avocado-framework-plugin-resultsdb (68.0)              - Avocado Plugin to propagate Job results to Resultsdb
    avocado-framework-plugin-result-html (68.0)            - Avocado HTML Report for Jobs
    avocado-framework-plugin-runner-remote (68.0)          - Avocado Runner for Remote Execution
    avocado-framework-plugin-glib (68.0)                   - Avocado Plugin for Execution of GLib Test Framework tests
    avocado-framework-plugin-runner-vm (68.0)              - Avocado Runner for libvirt VM Execution
    avocado-framework-plugin-runner-docker (68.0)          - Avocado Runner for Execution on Docker Containers
    avocado-framework-plugin-result-upload (68.0)          - Avocado Plugin to propagate Job results to remote host
    avocado-framework-plugin-loader-yaml (68.0)            - Avocado Plugin that loads tests from YAML files
    avocado-framework-plugin-varianter-yaml-to-mux (68.0)  - Avocado Varianter plugin to parse YAML file into variants
    avocado-framework-plugin-varianter-cit (68.0)          - Varianter with combinatorial capabilities
    avocado-framework-plugin-varianter-pict (68.0)         - Varianter with combinatorial capabilities by PICT

It there a reason why the package is not updated on PyPI?

**Comment by clebergnu** [comment]
Hi @pevogam, the avocado-framework-plugin-vt package was actually created by @lmr, and IIRC, there were a few issues with a PIP based install for Avocado-VT.

I guess it's time to double check that, and if everything looks good (or can be fixed) we can start maintaining that as we do for Avocado proper. Thanks!

**Comment by pevogam** [comment]
Sounds great! What is the chance for the 69.0 LTS version to be available for PyPI? I guess this is the plan for after 69.0?

**Comment by clebergnu** [comment]
Well, this "deployment check":

https://github.com/avocado-framework/avocado/pull/3043/commits/4ced2a5953517fd0f15f0415a12980db3ef387d2#diff-6cfe586f9022d00be6380e617897837aR72

Should guarantee that Avocado-VT works on installations done with pip (although it does so from a Git repo, there shouldn't be differences for a tar/wheel package).

If we get that reviewed/merged on this sprint, I can certainly start to maintain a package on pip starting with 69.0 (LTS).

**Comment by pevogam** [comment]
Hi @cleber, from your most recent release announcement I read:

> We also provide convenience packages for Avocado-VT.  Packages are
> offered for Python 2 (to be used with previous Avocado versions, such
> as the LTS ones) and Python 3 on Fedora 29 and Fedora 30.
> 
> Also, updated Python source and binary packages are available on PyPI:
> 
>  https://pypi.org/project/avocado-framework-plugins-vt/

I can see the 72.0 package is available on PyPI but a pip search still shows the old version:

```
avocado-framework (72.0)                               - Avocado Test Framework
avocado-epigenome (0.3.1)                              - Avocado is a package for learning a latent representation of the human epigenome.
avocado-framework-plugin-vt (57.4)                     - Avocado Plugin for Virtualization Testing
avocado-framework-plugins-vt (72.0)                    - Avocado Plugin for Virtualization Testing
avocado (2.4.3)                                        - Metadata APIs for Django
avocado-framework-plugin-golang (72.0)                 - Avocado Plugin for Execution of Golang tests
avocado-framework-plugin-robot (72.0)                  - Avocado Plugin for Execution of Robot Framework tests
avocado-framework-plugin-resultsdb (72.0)              - Avocado Plugin to propagate Job results to Resultsdb
avocado-framework-plugin-result-html (72.0)            - Avocado HTML Report for Jobs
avocado-framework-plugin-runner-remote (72.0)          - Avocado Runner for Remote Execution
avocado-framework-plugin-glib (72.0)                   - Avocado Plugin for Execution of GLib Test Framework tests
avocado-framework-plugin-runner-vm (72.0)              - Avocado Runner for libvirt VM Execution
avocado-framework-plugin-runner-docker (72.0)          - Avocado Runner for Execution on Docker Containers
avocado-framework-plugin-result-upload (72.0)          - Avocado Plugin to propagate Job results to remote host
avocado-framework-plugin-loader-yaml (72.0)            - Avocado Plugin that loads tests from YAML files
Django-Avocado (0.2.0)                                 - Delicious delayed and cached database-logging for django.
avocado-framework-plugin-varianter-yaml-to-mux (72.0)  - Avocado Varianter plugin to parse YAML file into variants
avocado-messenger-server (0.0.2)                       - Server for avocado_messenger
serrano (2.4.4)                                        - Hypermedia implementation for Avocado
avocado-framework-plugin-varianter-pict (72.0)         - Varianter with combinatorial capabilities by PICT
avocado-framework-plugin-varianter-cit (72.0)          - Varianter with combinatorial capabilities
```

In fact, it is even more confusing now because there is a version using the plural that is 72 but incompatible with the naming of the rest of the plugins. Any clue why is that so?

**Comment by pevogam** [comment]
Merging #2285 fixed this completely and now we have both correct name and version for the VT plugin:
```
avocado-framework (76.0)                               - Avocado Test Framework
avocado-epigenome (0.3.5)                              - Avocado is a package for learning a latent
                                                         representation of the human epigenome.
avocado-framework-plugin-vt (76.0)                     - Avocado Plugin for Virtualization Testing
avocado (2.4.3)                                        - Metadata APIs for Django
avocado-framework-plugin-golang (76.0)                 - Avocado Plugin for Execution of Golang tests
avocado-framework-plugin-resultsdb (76.0)              - Avocado Plugin to propagate Job results to
                                                         Resultsdb
avocado-framework-plugin-robot (76.0)                  - Avocado Plugin for Execution of Robot
                                                         Framework tests
avocado-framework-plugin-runner-remote (76.0)          - Avocado Runner for Remote Execution
avocado-framework-plugin-result-html (76.0)            - Avocado HTML Report for Jobs
avocado-framework-plugin-glib (76.0)                   - Avocado Plugin for Execution of GLib Test
                                                         Framework tests
avocado-framework-plugin-runner-docker (76.0)          - Avocado Runner for Execution on Docker
                                                         Containers
avocado-framework-plugin-runner-vm (76.0)              - Avocado Runner for libvirt VM Execution
avocado-framework-plugin-loader-yaml (76.0)            - Avocado Plugin that loads tests from YAML
                                                         files
avocado-framework-plugin-result-upload (76.0)          - Avocado Plugin to propagate Job results to
                                                         remote host
Django-Avocado (0.2.0)                                 - Delicious delayed and cached database-logging
                                                         for django.
avocado-framework-plugin-varianter-yaml-to-mux (76.0)  - Avocado Varianter plugin to parse YAML file
                                                         into variants
avocado-messenger-server (0.0.2)                       - Server for avocado_messenger
serrano (2.4.4)                                        - Hypermedia implementation for Avocado
avocado-framework-plugin-varianter-cit (76.0)          - Varianter with combinatorial capabilities
avocado-framework-plugin-varianter-pict (76.0)         - Varianter with combinatorial capabilities by
                                                         PICT
dinolemma (0.0.12)                                     - Simulate evolution of dinosaurs and avocado
                                                         trees
```
Good job! Closing.
