### ISSUE TITLE
Got "TestWarn" result just becuase "arping"  be killed with SIGKILL

### ISSUE THREAD

**Issue by yanan-fu** [avocado-framework/avocado-vt#2089]
In commit:  e1d50763511aa9848c6714adf66546102b6349bb,  utils_net.py:
```
+    def __arping(ip, macs, dev, timeout, session=None, **dargs):
+        func = process.getoutput
+        if session:
+            func = session.cmd_output
......
......
         try:
-            o = decode_to_text(process.system_output(arping_cmd, shell=True, verbose=False))
-        except process.CmdError:
+            o = func(arping_cmd, timeout=timeout, **dargs)
+        except (process.CmdError, aexpect.ShellError):
```

It add  `timeout` for func `process.getoutput`.  It is equal to the run time of `arping_cmd`.
Some times,  arping_cmd can't finish instantly,  cause process timeout, and try to kill it:
```
 824         def nuke_myself():                                                      
 825             self.result.interrupted = ("timeout after %ss"                      
 826                                        % (time.time() - self.start_time))       
 827             try:                                                                
 828                 kill_process_tree(self.get_pid(), sig, timeout=1)               
 829             except Exception:                                                   
 830                 try:                                                            
 831                     kill_process_tree(self.get_pid(), signal.SIGKILL,           
 832                                       timeout=1)                                
 833                     log.warning("Process '%s' refused to die in 1s after "      
 834                                 "sending %s to, destroyed it successfully "     
 835                                 "using SIGKILL.", self.cmd, sig)   
``` 

Sometimes, kill process with `sig` failed in 1s,  then use `signal.SIGKILL` to kill the process.
In this condition, case will got `Test.Warn` result,  but it really doesn't related with the test case,  we need `PASS` result.  

@balamuruhans  Please have a look at this issue, thanks !

**Comment by balamuruhans** [comment]
> It add timeout for func process.getoutput. It is equal to the run time of arping_cmd.
Some times, arping_cmd can't finish instantly, cause process timeout, and try to kill it:

@yanan-fu, by default we give `60.0` seconds as timeout and if arping_cmd doesn't respond then there might be 2 possibility,
1. ideally the VM's network went for toss.
2. there might be a race between the time VM responds before which script completes 60 seconds, for which we have used `utils_misc.wait_for()`.

Even without the commit  e1d5076, this issue is possible to hit. I have introduced the `timeout` so that we can make it configurable when we call `wait_for_login()`. Please share your thoughts on this, thank you.

**Comment by yanan-fu** [comment]
@balamuruhans  It is not related with `wait_for_login`.  The problem is:
1. old design use `timeout=None` in `process.getoutput` (`process.system_output`,  it is ok to use getoutput instead of system_output), then it will wait until `arping_cmd` finished
2. New design  add `timeout` for `process.getoutput`. Here, it is not correct to use the running time for `arping_cmd` as the `timout` for `process.getoutput`.  launch `arping_cmd` need time.

**Comment by balamuruhans** [comment]
@yanan-fu okay, can this change solves the issue as it affects only `arping_cmd` ?

```patch
diff --git a/virttest/utils_net.py b/virttest/utils_net.py
index f68a173e..ce05d9aa 100644
--- a/virttest/utils_net.py
+++ b/virttest/utils_net.py
@@ -3175,7 +3175,7 @@ def verify_ip_address_ownership(ip, macs, timeout=60.0, devs=None,                                                                                       
             arping_cmd = "%s -f -c3 -w%d -I %s %s" % (arping_bin, int(timeout),
                                                       dev, ip)
         try:
-            o = func(arping_cmd, timeout=timeout, **dargs)
+            o = func(arping_cmd, **dargs)
         except (process.CmdError, aexpect.ShellError):
             return False
         return bool(regex.search(o))

```

**Comment by yanan-fu** [comment]
@balamuruhans  yeah, as my understanding, it can solve the problem.

**Comment by balamuruhans** [comment]
@yanan-fu, Thank you for reporting and helping to fix this issue, I have sent PR for it https://github.com/avocado-framework/avocado-vt/pull/2093.
It would be great if you could try running the failing test scenario with the this PR. Thanks!
