### ISSUE TITLE
avocado bootstrap throw error message 

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#2249]
<pre>(p3-ve) [root@chunfulap2 avocado-vt]# avocado vt-bootstrap --vt-type libvirt
<font color="#EF2929">Error running method &quot;configure&quot; of plugin &quot;vt&quot;: argument --vt-config: conflicting option string: --vt-config</font>
<font color="#EF2929">Error running method &quot;configure&quot; of plugin &quot;vt-list&quot;: argument --vt-list-guests: conflicting option string: --vt-list-guests</font>
</pre>

Note:python version is 3.4

**Comment by sathnaga** [comment]
try this PR, if any help, https://github.com/avocado-framework/avocado-vt/pull/2194

**Comment by chunfuwen** [comment]
@

**Comment by chunfuwen** [comment]
@sathnaga, is it a known issue?

**Comment by clebergnu** [comment]
@chunfuwen this may have to do with your environment having a left over deployment when the module name was different (see #ade4e809ce8ff2c92c685827f7742e8e5e417dcc).  Then, you'd have two plugins (versions) trying to setup the same command line option.  Look for `avocado_framework_plugins_vt.egg-info` and `avocado_plugins_vt.egg-info` in your filesystem.

**Comment by chunfuwen** [comment]
@clebergnu, thank for your help, that work to me after avocado_plugins_vt.egg-info deletion in my local environment.
