### ISSUE TITLE
missed show-job-log option in avocado run 

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#2339]
I remember in earlier avocado version, show-job-log is supported in avocado run, which is very useful to do test case debugging since it directly output logs to console . 
In the current avocado release, I can not find it. Do we have alternative option for it? or just leave it away ?

**Comment by clebergnu** [comment]
It's still available, but under the *core* option --show. You can use
something like:

avocado --show=test run -- boot

**Comment by chunfuwen** [comment]
@clebergnu ,thank for answering
