### ISSUE TITLE
Deprecate or remove compatibility with Avocado 52.X LTS 

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado-vt#2408]
Avocado-VT still carries compatibility code with Avocado 52.X LTS, even though 69.X LTS has been out for a while.

Are there any users out there that still need to use the latest Avocado-VT with Avocado 52.LTS?  On the (Cirrus) CI, we're only testing Avocado-VT with LTS version 69.0.

@luckyh would you be able to answer if there are still a use case for latest Avocado-VT + Avocado 52.0 LTS?  If not, I'll go ahead and work on the demise of the compatibility layer.

**Comment by luckyh** [comment]
@clebergnu based on my observations, it's less likely that there are users still using modern Avocado-VT + Avocado 52.0 LTS, so I think it's the time to move forward, thanks.

**Comment by pevogam** [comment]
I also hope we can move forward to removing python2 compatibility too in the future. On Fedora 31 container I encounter the following issue:

```
# /usr/bin/python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    pre_post_plugin_type(): [
  File "setup.py", line 76, in pre_post_plugin_type
    from avocado.core.plugin_interfaces import JobPreTests as Pre
  File "/usr/lib/python3.7/site-packages/avocado/__init__.py", line 29, in <module>
    from avocado.core.job import main
  File "/usr/lib/python3.7/site-packages/avocado/core/job.py", line 31, in <module>
    from . import data_dir
  File "/usr/lib/python3.7/site-packages/avocado/core/data_dir.py", line 35, in <module>
    from . import settings
  File "/usr/lib/python3.7/site-packages/avocado/core/settings.py", line 292, in <module>
    settings = Settings()  # pylint: disable-msg=invalid-name
  File "/usr/lib/python3.7/site-packages/avocado/core/settings.py", line 133, in __init__
    dispatcher = SettingsDispatcher()
  File "/usr/lib/python3.7/site-packages/avocado/core/settings_dispatcher.py", line 37, in __init__
    super(SettingsDispatcher, self).__init__('avocado.plugins.settings')
  File "/usr/lib/python3.7/site-packages/avocado/core/extension_manager.py", line 62, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (avocado-framework 74.0 (/usr/lib/python3.7/site-packages), Requirement.parse('avocado-framework<70.0,>=68.0'))
```
Can any of you reproduce this? It seems to be related to compatibility with the avocado plugin where using python3 requires avocado version between 68.0 and 70.0 instead of python2. The same issue does no occur on Fedora 30 for example.

**Comment by pevogam** [comment]
@clebergnu @luckyh Do you think it is worth creating a new issue for this or is it something obvious or something you haven't experienced on F31 yourself?

**Comment by luckyh** [comment]
> I also hope we can move forward to removing python2 compatibility too in the future. On Fedora 31 container I encounter the following issue:
> 
> ```
> # /usr/bin/python3 setup.py build
> Traceback (most recent call last):
>   File "setup.py", line 116, in <module>
>     pre_post_plugin_type(): [
>   File "setup.py", line 76, in pre_post_plugin_type
>     from avocado.core.plugin_interfaces import JobPreTests as Pre
>   File "/usr/lib/python3.7/site-packages/avocado/__init__.py", line 29, in <module>
>     from avocado.core.job import main
>   File "/usr/lib/python3.7/site-packages/avocado/core/job.py", line 31, in <module>
>     from . import data_dir
>   File "/usr/lib/python3.7/site-packages/avocado/core/data_dir.py", line 35, in <module>
>     from . import settings
>   File "/usr/lib/python3.7/site-packages/avocado/core/settings.py", line 292, in <module>
>     settings = Settings()  # pylint: disable-msg=invalid-name
>   File "/usr/lib/python3.7/site-packages/avocado/core/settings.py", line 133, in __init__
>     dispatcher = SettingsDispatcher()
>   File "/usr/lib/python3.7/site-packages/avocado/core/settings_dispatcher.py", line 37, in __init__
>     super(SettingsDispatcher, self).__init__('avocado.plugins.settings')
>   File "/usr/lib/python3.7/site-packages/avocado/core/extension_manager.py", line 62, in __init__
>     plugin = ep.load()
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
>     self.require(*args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
>     items = working_set.resolve(reqs, env, installer, extras=self.extras)
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (avocado-framework 74.0 (/usr/lib/python3.7/site-packages), Requirement.parse('avocado-framework<70.0,>=68.0'))
> ```
> 
> Can any of you reproduce this? It seems to be related to compatibility with the avocado plugin where using python3 requires avocado version between 68.0 and 70.0 instead of python2. The same issue does no occur on Fedora 30 for example.

@pevogam I wasn't able to reproduce this issue on my F31 box, would you please help provide the details about how your environment were configured?

**Comment by pevogam** [comment]
Hi @luckyh, did you try building the package while you have avocado already installed? You might need at least these steps:
```
dnf localinstall -y /mnt/local/packages/lxc/python3-avocado-76.0-1.fc31.noarch.rpm /mnt/local/packages/lxc/python3-avocado-common-76.0-1.fc31.noarch.rpm
```
A more complete list of steps would be
```
lxc-create -t download -n c40 -- --dist fedora --release 31 --arch amd64 --keyserver hkp://p80.pool.sks-keyservers.net:80
<enable networking on the container>
lxc-attach -n c40
dnf install -y wget rpm-build
wget https://github.com/avocado-framework/avocado/archive/77.0.tar.gz
tar xf 77.0.tar.gz
mkdir -p "$HOME"/rpmbuild/SPECS "$HOME"/rpmbuild/SOURCES
mv 77.0.tar.gz "$HOME"/rpmbuild/SOURCES/avocado-vt-77.0.tar.gz
dnf install -y 'dnf-command(builddep)'
dnf builddep -y avocado-vt-77.0/avocado-plugins-vt.spec
rpmbuild -ba avocado-vt-77.0/avocado-plugins-vt.spec
```
assuming you try to then rebuild the avocado-vt RPM after installing the avocado RPMs.

**Comment by clebergnu** [comment]
This was completed with https://github.com/avocado-framework/avocado-vt/pull/2611
