### ISSUE TITLE
cirrus CI failed due to missing libvirt client packages

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#2444]
In PR:https://github.com/avocado-framework/avocado-vt/pull/2442,
cirrus CI failed when execute virsh version to get libvirt version.
It sound like libvirt client tools is not installed first. 
How to install libvirt client: yum install  libvirt libvirt-python libguestfs-tools 
see more details from:
https://github.com/avocado-framework/avocado-vt/pull/2442/checks?check_run_id=464216415

**Comment by chunfuwen** [comment]
It need install below packages in containerized fedora or centos images:
yum install qemu-kvm libvirt libvirt-python libguestfs-tools virt-install

**Comment by chunfuwen** [comment]
@clebergnu 
@luckyh
Anyone can help on this ?

**Comment by clebergnu** [comment]
Hi @chunfuwen ,

While it's possible to add those packages to the container used on those CI checks, I don't see *why* it should be required on bootstraps that do *not* deal with libvirt.  Do you intend to make libvirt and all those other packages requirements even to `--vt-type=qemu` kind of bootstrap?

**Comment by chunfuwen** [comment]
I add new module libvirtd_decorator.py under avocado-vt/virttest/,which make use of the method:  libvirt_version.version_compare(5, 6, 0) and the later call "virsh version" command. Honestly , I don't intend to make  libvirt and all those other packages requirements as kind of bootstrap, do we have workaround solution for this ?

**Comment by smitterl** [comment]
FYI, we have a "hidden, some kind of" dependency to libvirt even for qemu-only test cases: https://github.com/avocado-framework/avocado-vt/issues/2437
With this, the only reasons to have libvirt dependency would be:
1. set up network for qemu guest that works like default `virbr0` from libvirt
2. allow for decorator module import during bootstrap even if `utils_libvirtd.Libvirtd` is never used


This is a trend I would rather want to stop as soon as possible to keep things separate.

Isn't it a bit of an irony that the handling `libvirtd split` whose goal is to _decouple_ would cause test framework to be more _coupled_? 😕

**Comment by clebergnu** [comment]
@smitterl you're right, the base Avocado-VT framework should not be coupled to libvirt. With regards to the points you listed:

1) I don't think using a libvirtd created bridge `virbr0` is *required*; if it's being proposed to be required, I definitely agree that it should not (`nettype = user` can always be used).
2) I think it's not ideal, but acceptable, to implement a `libvirt_*` module that, when actively used, would require some level of libvirt installation. But requiring libvirt (say `virsh`) even if the code is never actively used, is just wrong

The Cirrus CI jobs are actually doing what they're supposed to do, that is, making sure we don't increase the coupling and requirements just to have Avocado-VT installed and deployed.

**Comment by chunfuwen** [comment]
@clebergnu 
@smitterl 
If a libvirt_* module is provisioned, I am fine to find another way to detect libvirt version(such as /usr/sbin/libvirtd --version, /usr/sbin/virtqemud --version),rather than execute command :virsh version

**Comment by chunfuwen** [comment]
@clebergnu 
Regarding https://github.com/avocado-framework/avocado-vt/pull/2442 , I had removed the logic to detect libvirt version by virsh --version. Instead I use either libvirtd -V or virtqemud -V(future feature for split daemon), but cirrus CI still failed  since it sounds like libvirt modules still  are not available in the container images.

**Comment by chunfuwen** [comment]
@clebergnu
@luckyh
Anyone can help move it forward?

**Comment by chunfuwen** [comment]
issue is resolved
