### ISSUE TITLE
Could not connect to monitor 'qmpmonitor1' of Win10 guest

### ISSUE THREAD

**Issue by rdkdd** [avocado-framework/avocado-vt#2509]
Hello,
I have a problem in running command:
```
avocado --show all run --vt-guest-os Windows.Win10.x86_64 unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads --vt-extra-params mem=2048 skip_hash=yes unattended_file=/mnt/tests/install-compose/ks/win10-64-autounattend.xml image_name=/mnt/images/Windows-10-20200405.0-x86_64 cdrom_cd1='/var/lib/avocado/data/avocado-vt/isos/windows/w10_64_latest.iso' cdkey=2NFFP-YQ4GC-24J7Q-B86RP-XTPKM
```

which shows an error `Could not connect to monitor 'qmpmonitor1'`.
I have no such a problem with RHEL guest.
I can not get any output from `rlwrap -C qmp socat STDIO UNIX:$path-to-the-QMP-unix-socket
` (as is desribed in [QMP documentation](https://wiki.qemu.org/Documentation/QMP)), so maybe the qmp socket is not working..
Here is my [job.log](https://github.com/avocado-framework/avocado-vt/files/4456078/job.log).

**Comment by ldoktor** [comment]
Based on offline communication this is not an Avocado-vt issue, but NFS share-related issue.
