### ISSUE TITLE
Remove avocado.core.settings calls and replace by future.settings

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado-vt#2596]
`avocado.core.settings` will be replaced by `avocado.core.future.settings` soon.

All configuration options should be registered using `settings.register_option()` and when getting values, code should do that from the config dictionary (if available)

```python
bar = config.get('foo.bar')
```
 or via `settings.as_dict()` method, when `config` is not available on the current method:

```python
from avocado.core.future.settings import settings
config = settings.as_dict()
bar = config.get('foo.bar')
```

This is part of BP001 (https://avocado-framework.readthedocs.io/en/latest/blueprints/BP001.html) and an effort to remove all "default values" spread on the code.

**Comment by clebergnu** [comment]
This is done with the compatibility layer added in https://github.com/avocado-framework/avocado-vt/pull/2708
