### ISSUE TITLE
Avocado VT RPM doesn't build

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#2637]
Hi, it seems that a recent change prevents the RPM from being built any longer:

```
+ /usr/bin/python3 setup.py install --root /root/rpmbuild/BUILDROOT/avocado-plugins-vt-80.0-1.fc31.x86_64 --skip-build
Traceback (most recent call last):
  File "setup.py", line 118, in <module>
    pre_post_plugin_type(): [
  File "setup.py", line 76, in pre_post_plugin_type
    from avocado.core.plugin_interfaces import JobPreTests as Pre
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/__init__.py", line 28, in <module>
    from avocado.core.test import Test
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/__init__.py", line 19, in <module>
    from .dispatcher import InitDispatcher
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/dispatcher.py", line 23, in <module>
    from .enabled_extension_manager import EnabledExtensionManager
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/enabled_extension_manager.py", line 20, in <module>
    from .settings import settings
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/settings.py", line 618, in <module>
    settings = Settings()  # pylint: disable-msg=invalid-name
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/settings.py", line 271, in __init__
    self._append_config_paths()
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/settings.py", line 281, in _append_config_paths
    dispatcher = SettingsDispatcher()
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/settings_dispatcher.py", line 37, in __init__
    super(SettingsDispatcher, self).__init__('avocado.plugins.settings')
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/extension_manager.py", line 62, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'netaddr' distribution was not found and is required by the application
error: Bad exit status from /var/tmp/rpm-tmp.sAltKT (%install)
```

The reason for this failure is that the function `pre_post_plugin_type()` in `setup.py` is executed and imports like

```python
from avocado.core.plugin_interfaces import JobPreTests as Pre
```

which triggers a search of all dependencies from the `Requires:` SPEC file clauses in addition to the `BuildRequires:` clauses which are the only ones we actually have to require.

**Comment by PaulYuuu** [comment]
Hello @pevogam 
I also hit another issue but I believe the reason is the same as yours. After I revert https://github.com/avocado-framework/avocado/pull/3980, VT can work on my environment.

Cc @clebergnu here to help.

**Comment by pevogam** [comment]
Hi @PaulYuuu, thanks for adding a confirmation to the issue. From my superficial check it seems that the PR 3980 was merged 12 hours ago and I reported the problem yesterday so I think I experienced it beforehand. But let's see what others have to say about this.

**Comment by clebergnu** [comment]
@pevogam what kind of system are you building the RPM on? Are you running a `make rpm` or some other type of commands?

**Comment by pevogam** [comment]
> @pevogam what kind of system are you building the RPM on? Are you running a `make rpm` or some other type of commands?

I am using a blank Fedora 31 LXC container:
```
[root@c20 ~]# cat /etc/os-release 
NAME=Fedora
VERSION="31 (Container Image)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Container Image)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
```

I am not using anything special as far as I can think:
```
[root@c20 ~]# rpmbuild -ba /mnt/local/../avocado-vt.spec
...
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd avocado-vt-80.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ RPM_EC=0
++ jobs -p
+ exit 0
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd avocado-vt-80.0
+ /usr/bin/python3 setup.py build
+ RPM_EC=0
++ jobs -p
+ exit 0
+ umask 022
+ cd /root/rpmbuild/BUILD
+ '[' /root/rpmbuild/BUILDROOT/avocado-plugins-vt-80.0-1.fc31.x86_64 '!=' / ']'
+ rm -rf /root/rpmbuild/BUILDROOT/avocado-plugins-vt-80.0-1.fc31.x86_64
++ dirname /root/rpmbuild/BUILDROOT/avocado-plugins-vt-80.0-1.fc31.x86_64
+ mkdir -p /root/rpmbuild/BUILDROOT
+ mkdir /root/rpmbuild/BUILDROOT/avocado-plugins-vt-80.0-1.fc31.x86_64
+ cd avocado-vt-80.0
+ /usr/bin/mkdir -p /root/rpmbuild/BUILDROOT/avocado-plugins-vt-80.0-1.fc31.x86_64/etc/avocado/conf.d
+ /usr/bin/python3 setup.py install --root /root/rpmbuild/BUILDROOT/avocado-plugins-vt-80.0-1.fc31.x86_64 --skip-build
Traceback (most recent call last):
  File "setup.py", line 118, in <module>
    pre_post_plugin_type(): [
  File "setup.py", line 76, in pre_post_plugin_type
    from avocado.core.plugin_interfaces import JobPreTests as Pre
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/__init__.py", line 28, in <module>
    from avocado.core.test import Test
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/__init__.py", line 19, in <module>
    from .dispatcher import InitDispatcher
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/dispatcher.py", line 23, in <module>
    from .enabled_extension_manager import EnabledExtensionManager
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/enabled_extension_manager.py", line 20, in <module>
    from .settings import settings
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/settings.py", line 618, in <module>
    settings = Settings()  # pylint: disable-msg=invalid-name
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/settings.py", line 271, in __init__
    self._append_config_paths()
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/settings.py", line 281, in _append_config_paths
    dispatcher = SettingsDispatcher()
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/settings_dispatcher.py", line 37, in __init__
    super(SettingsDispatcher, self).__init__('avocado.plugins.settings')
  File "/root/rpmbuild/BUILD/avocado-80.0/avocado/core/extension_manager.py", line 62, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'netaddr' distribution was not found and is required by the application
error: Bad exit status from /var/tmp/rpm-tmp.Wa18Lc (%install)
    bogus date in %changelog: Fri Jan 21 2020 Plamen Dimitrov <pdimitrov@pevogam.com> - 75.0-1
    Bad exit status from /var/tmp/rpm-tmp.Wa18Lc (%install)
```

Maybe it is best to transfer further ongoing questions about this in the corresponding issue instead of here but as you can see also the errors relate to missing installation phase dependencies that are only defined with `Requires` and not with `BuildRequires` and can be traced to the import within `pre_post_plugin_type()`.

**Comment by clebergnu** [comment]
@pevogam FIY, on a Fedora 31 machine, after `make rpm` I get:

```
ll BUILD/RPM/
total 25168
-rw-r--r--. 1 cleber mock   8351358 Jul  7 13:10 avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.src.rpm
-rw-rw-r--. 1 cleber cleber  312403 Jul  7 13:10 build.log
-rw-rw-r--. 1 cleber cleber    2871 Jul  7 13:09 hw_info.log
-rw-rw-r--. 1 cleber cleber   14785 Jul  7 13:10 installed_pkgs.log
-rw-r--r--. 1 cleber mock   8497897 Jul  7 13:10 python2-avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.noarch.rpm
-rw-r--r--. 1 cleber mock   8508723 Jul  7 13:10 python3-avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.noarch.rpm
-rw-rw-r--. 1 cleber cleber   67971 Jul  7 13:10 root.log
-rw-rw-r--. 1 cleber cleber    1090 Jul  7 13:10 state.log
```

**Comment by pevogam** [comment]
> @pevogam FIY, on a Fedora 31 machine, after `make rpm` I get:
> 
> ```
> ll BUILD/RPM/
> total 25168
> -rw-r--r--. 1 cleber mock   8351358 Jul  7 13:10 avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.src.rpm
> -rw-rw-r--. 1 cleber cleber  312403 Jul  7 13:10 build.log
> -rw-rw-r--. 1 cleber cleber    2871 Jul  7 13:09 hw_info.log
> -rw-rw-r--. 1 cleber cleber   14785 Jul  7 13:10 installed_pkgs.log
> -rw-r--r--. 1 cleber mock   8497897 Jul  7 13:10 python2-avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.noarch.rpm
> -rw-r--r--. 1 cleber mock   8508723 Jul  7 13:10 python3-avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.noarch.rpm
> -rw-rw-r--. 1 cleber cleber   67971 Jul  7 13:10 root.log
> -rw-rw-r--. 1 cleber cleber    1090 Jul  7 13:10 state.log
> ```

Do you have all the dependencies already installed? Is it a blank virtual machine/container or a machine avocado RPMs were previously installed on? If the dependencies above are already present due to previous installation this won't be detected.

**Comment by clebergnu** [comment]
> > @pevogam FIY, on a Fedora 31 machine, after `make rpm` I get:
> > ```
> > ll BUILD/RPM/
> > total 25168
> > -rw-r--r--. 1 cleber mock   8351358 Jul  7 13:10 avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.src.rpm
> > -rw-rw-r--. 1 cleber cleber  312403 Jul  7 13:10 build.log
> > -rw-rw-r--. 1 cleber cleber    2871 Jul  7 13:09 hw_info.log
> > -rw-rw-r--. 1 cleber cleber   14785 Jul  7 13:10 installed_pkgs.log
> > -rw-r--r--. 1 cleber mock   8497897 Jul  7 13:10 python2-avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.noarch.rpm
> > -rw-r--r--. 1 cleber mock   8508723 Jul  7 13:10 python3-avocado-plugins-vt-80.0-1.20200707git8475d30e.fc31.noarch.rpm
> > -rw-rw-r--. 1 cleber cleber   67971 Jul  7 13:10 root.log
> > -rw-rw-r--. 1 cleber cleber    1090 Jul  7 13:10 state.log
> > ```
> 
> Do you have all the dependencies already installed? Is it a blank virtual machine/container or a machine avocado RPMs were previously installed on? If the dependencies above are already present due to previous installation this won't be detected.

@pevogam `make rpm` makes use of mock, which creates a "container-like" environment that gets cleared every time.  That has helped us to catch this type of dependency problem before.

**Comment by pevogam** [comment]
I will have to take a look to see if `make rpm` does some extra preparation of any kind. My general building process involves direct usage of the `rpmbuild` utility and the spec file (which should be possible after all). Perhaps this could still fix a problem for @PaulYuuu who had his more recent issue a day after me.

**Comment by clebergnu** [comment]
> I will have to take a look to see if `make rpm` does some extra preparation of any kind. My general building process involves direct usage of the `rpmbuild` utility and the spec file (which should be possible after all). Perhaps this could still fix a problem for @PaulYuuu who had his more recent issue a day after me.

`mock`, used on `make rpm` will install what Fedora considers a base build environment (packages that don't need to be specified as a build requirement) and the ones listed in the spec file too.

With regards to the issue found by @PaulYuuu , I could reproduce it, and it was indeed fixed by #2639 . I think your issue has to do with the `make rpm` .vs. `rpmbuild` approach.

**Comment by pevogam** [comment]
Alright, thanks for the hints, I will spend some time debugging and hopefully come back to this.

**Comment by pevogam** [comment]
This issue has been fixed in recent avocado VT releases. In the case of needed future reference: the issue only appeared when Avocado VT was preinstalled on a container and a local RPM was built in the same container.
