### ISSUE TITLE
avocado-vt bootstrap failed intermittently

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#2710]
Environment:
1)avocado version:69.3lts
2)avocado-vt:master
3)tp-libvirt:master
Steps:
Execute : avocado vt-bootstrap --vt-type libvirt --vt-no-downloads command under tp-libvirt,
and some errors throw out as below:

Avocado crashed:
Traceback (most recent call last):
  File "/root/code/p3-ve/bin/avocado", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/code/avocado/scripts/avocado", line 75, in <module>
    sys.exit(app.run())
  File "/root/code/avocado/avocado/core/app.py", line 91, in run
    return method(self.parser.args)
  File "/root/code/avocado-vt/avocado_vt/plugins/vt_bootstrap.py", line 100, in run
    bootstrap.bootstrap(options=config, interactive=True)
  File "/root/code/avocado-vt/virttest/bootstrap.py", line 963, in bootstrap
    create_host_os_cfg(options)
  File "/root/code/avocado-vt/virttest/bootstrap.py", line 355, in create_host_os_cfg
    vendor = cpu.get_vendor() if hasattr(cpu, 'get_vendor') else cpu.get_cpu_vendor_name()
  File "/root/code/avocado/avocado/utils/cpu.py", line 111, in get_cpu_vendor_name
    if _list_matches(cpu_info, identifier):
  File "/root/code/avocado/avocado/utils/cpu.py", line 36, in _list_matches
    match = re.search(pattern, content)
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like objec

**Comment by chloerh** [comment]
I have been trying to reproduce this error but failing.  According to the message: 
`TypeError: cannot use a string pattern on a bytes-like objec`
We could say that 'pattern' is 'string' type, which is odd.  

```
def get_cpu_vendor_name():
    """
    Get the current cpu vendor name

    :returns: string 'intel' or 'amd' or 'power7' depending on the
         current CPU architecture.
    :rtype: `string`
    """
    vendors_map = {
        'intel': (b"GenuineIntel", ),
        'amd': (b"AMD", ),
        'power7': (b"POWER7", ),
        'power8': (b"POWER8", )
    }

    cpu_info = _get_cpu_info()
    for vendor, identifiers in vendors_map.items():
        for identifier in identifiers:
            if _list_matches(cpu_info, identifier):
                return vendor
    return None
```

According to code above, all patterns are defined as 'bytes' type.  And after I changed line
 `        'intel': (b"GenuineIntel", ),`  
to 
`        'intel': ("GenuineIntel", ),`

by removing the 'b', then the error appeared.  But never happens with the original code. 

I'm not sure why this happened.  I guess I might need more info to do more research.

**Comment by chloerh** [comment]
Ok, I think I have an answer.

According to info you provided:
`File "/root/code/p3-ve/bin/avocado", line 7, in` 

Looks like your avocado was installed under virtual env.

But look here:
```
File "/usr/lib64/python3.6/re.py", line 182, in search
return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like objec
```

Here, it's not calling 're' from virtual env, but directly from system. 
It should be `/root/code/p3-ve/lib64/python3.6/re.py' `

Therefore, I guess the installation was not correct.  
I hope this helps.

**Comment by chunfuwen** [comment]
def get_cpu_vendor_name():
    """
    Get the current cpu vendor name

    :returns: string 'intel' or 'amd' or 'power7' depending on the
         current CPU architecture.
    :rtype: `string`
    """
    vendors_map = {
        'intel': (b"GenuineIntel", ),
        'amd': (b"AMD", ),
        'power7': (b"POWER7", ),
        'power8': (b"POWER8", )
    }

    cpu_info = _get_cpu_info()
    for vendor, identifiers in vendors_map.items():
        for identifier in identifiers:
            if _list_matches(cpu_info, identifier):
                return vendor
    return None
*********************************************************
this is issue in vendors_map, empty string need be initialized as bytes empty string

    vendors_map = {
        'intel': (b"GenuineIntel", b'' ),
        'amd': (b"AMD", b''),
        'power7': (b"POWER7", b''),
        'power8': (b"POWER8", b'')
    }

**Comment by chunfuwen** [comment]
(p3-ve) [root@hp-dl360g9-16 code]# ls /root/code/p3-ve/lib64/python3.6/re.py
ls: cannot access '/root/code/p3-ve/lib64/python3.6/re.py': No such file or directory

Kindly remind, re.py doesn't exist in virtualenv.

**Comment by chloerh** [comment]
This is what I did to check whether 're' exists or not

```
# virtualenv test_venv
Using base prefix '/usr'
New python executable in /root/test_venv/bin/python3.6
Also creating executable in /root/test_venv/bin/python
Installing setuptools, pip, wheel...done.
[root@intel-chiefriver-02 ~]# source test_venv/bin/activate
(test_venv) [root@intel-chiefriver-02 ~]# python
Python 3.6.8 (default, Jun 26 2020, 12:10:09) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.search('aaa',b'bbb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/test_venv/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
>>> 

```

As it shows, 're.py' does exist under virtual env.

Then I checked your environment, and found this: pyvenv.cfg

May I ask how did you create your virtual env?  It looks like your virtual env was not created by command 'virtualenv', but by 'python -m venv',  am I right?  
Could you provide the command that you run to create the virtualenv?  That would be really helpful.

**Comment by PaulYuuu** [comment]
@sathnaga I believe you know more, do you have a plan to backport https://github.com/avocado-framework/avocado/pull/3350 to 69lts?

**Comment by sathnaga** [comment]
@PaulYuuu It's more of a cherry-pick to the lts version,  awaiting comment from @clebergnu , discussion here, https://github.com/avocado-framework/avocado-vt/pull/2455#issuecomment-666220878

**Comment by chloerh** [comment]
> @sathnaga I believe you know more, do you have a plan to backport [avocado-framework/avocado#3350](https://github.com/avocado-framework/avocado/pull/3350) to 69lts?

Actually, I don't think https://github.com/avocado-framework/avocado/pull/3350 is the cause of this issue.   Since the issue is running on 69lts, and the related pull requests are not merged.

**Comment by chloerh** [comment]
It looks like that your avocado test environment was created by 
```
$ python -m venv VENV_PATH
....
$ pip3 install avocado-framework
```
May I ask if that's true? 
I'm wondering if it's true, then how did you manage installing avocado 69.3. I have tried and installed avocado 80.0. 
Then I thought, maybe after installing by pip,  avocado was installed again?

**Comment by chloerh** [comment]
After discussion, this issue is very clear now.  The version of installed avocado is 69.0, not 69.3, I guess this issue could be closed now

**Comment by chunfuwen** [comment]
not reproduced on 69.3, close it firstly
