### ISSUE TITLE
update python to 3.6 and remove allow_failures for python 3.4 in avocado-vt travis.yml

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#2794]
I assume it may be right time to update python from 3.4 to 3.6,and remove allow failure as well since some contributors prefer some module functionality on python 3.6 afterwards

**Comment by pevogam** [comment]
Hi @chunfuwen, in fact the CI for python 3 versions right now is pretty superficial so updating it and disallowing failures is more than welcome.

**Comment by clebergnu** [comment]
It's way past time indeed! In fact, I'd advocate towards having jobs for multiple Python versions, given that up to 5, IIRC, will run in parallel on Travis.

**Comment by chunfuwen** [comment]
The issue was already addressed by merged  PR:https://github.com/avocado-framework/avocado-vt/pull/2797 ,so close it
