### ISSUE TITLE
Missing 84.0 release tag

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#2937]
We have release 83.0 and release 85.0 but not release 84.0. This is not just a minor inconsistency but it disturbs the release process of [other](https://github.com/intra2net/avocado-i2n) plugins down the line that sync with both the Avocado and Avocado VT versions when releasing. Even though we know these tags are a bit superficial no explicit decision was made about how to deal with them in the respective RFC after 82.0 leading to ambiguity and some tags missing while some tags added back.

As 85.0 tag was added but 85.0 is not announced LTS, I recommend adding the tag 84.0 retrospectively at a commit with an approximately similar date like the commit for the Avocado 80.0 tag. This will fix our release process and remedy some of the problems that arose from the unfinished RFC.

**Comment by clebergnu** [comment]
OK, I didn't realize you relied on having a matching Avocado-VT tag/release for every Avocado tag/release.  And as explained in the mailing list, it was my mistake.

I'm tagging 3769db6a6b4b3b7f14a3581cecd64e4e8dffd7b3 as 84.0.  It should now be available: https://github.com/avocado-framework/avocado-vt/tree/84.0

**Comment by pevogam** [comment]
Alright, thanks a lot! Case closed ^^
