### ISSUE TITLE
Avocado-vt plugins can't work

### ISSUE THREAD

**Issue by rbian** [avocado-framework/avocado-vt#308]
As avocado changed plugin architecture:
avocado-framework/avocado/pull/921
avocado-framework/avocado-vt/pull/303

Avocado-vt plugins can't work now:

1. make link command
22:22:18 2015-12-21 22:22:18,555     INFO|Linking avocado-vt
22:22:18 for MAKEFILE in ../autotest ../avocado-vt ../tp-libvirt;\
22:22:18 		do AVOCADO_DIRNAME=avocado make -C $MAKEFILE link &>/dev/null && echo ">> LINK $MAKEFILE" || echo ">> SKIP $MAKEFILE";\
22:22:18 	done
22:22:18 >> SKIP ../autotest
22:22:18 >> SKIP ../avocado-vt
22:22:18 >> SKIP ../tp-libvirt

2. vt-bootstrap command 
22:22:18 2015-12-21 22:22:18,583     INFO|Bootstrap avocado-vt...
22:22:18 usage: avocado [-h] [-v] [--config CONFIG_FILE] {} ...
22:22:18 avocado: error: argument subcommand: invalid choice: 'vt-bootstrap' (choose from )

**Comment by lmr** [comment]
@rbian the way to use avocado has changed, now in order for the plugins to work they must be installed. I need to coordinate with @clebergnu how we are going to communicate that to our users.

**Comment by lmr** [comment]
I'm sorry for the inconvenience, by the way

**Comment by clebergnu** [comment]
@rbian you should be able to get Avocado-VT up and running out of the source tree simply by:

1) Enabling plugin entry points: you can do that either by running `$ python setup.py develop` or `$ python setup.py install`. The first one is recommended if you're developing Avocado-VT.

2) Linking the Avocado-VT configuration file by running `$ make link` in the **Avocado** repo.

Let me know if you still find any issues after that.

**Comment by clebergnu** [comment]
@rbian btw, if you still find any issues, please notify us be reopening this issue. Thanks!

**Comment by rbian** [comment]
After installation, the command still can't work:
# avocado list
Failed to load plugin from module "avocado_vt.plugins.vt_list": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
Failed to load plugin from module "avocado_vt.plugins.vt": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)

# avocado vt-bootstrap
Failed to load plugin from module "avocado_vt.plugins.vt_list": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
Failed to load plugin from module "avocado_vt.plugins.vt": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)

**Comment by clebergnu** [comment]
@rbian the error messages are correct, you need to execute `avocado vt-bootstrap` to have both plugins working.

The question is: what happens **when** and **after** you run `avocado vt-bootstrap`?

Can you provide the full output of  `$ avocado vt-bootstrap` ?

**Comment by rbian** [comment]
@clebergnu , avocado vt-bootstrap output message is the same:
\# avocado vt-bootstrap
Failed to load plugin from module "avocado_vt.plugins.vt_list": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
Failed to load plugin from module "avocado_vt.plugins.vt": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)

**Comment by will-Do** [comment]
Reopen this issue

**Comment by rbian** [comment]
@clebergnu , it works well as your instruction on my fedora host. I always get error messages on my rhel7 host. It's weird.

**Comment by clebergnu** [comment]
@rbian I'll try to reproduce on a EL7 box.

**Comment by clebergnu** [comment]
Trying to reproduce, the distro:

```
[cleber@localhost ~]$  cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)
```

The Avocado repo used:

```
[cleber@localhost avocado]$ git show 
commit 4bfd40f234b5873b1a138e24b431da875c75bc3a
Merge: a78d3a2 56d1b41
Author: Cleber Rosa <crosa@redhat.com>
Date:   Tue Dec 22 19:47:35 2015 -0200

    Merge branch 'release_0_31_fixes'
```

The Avocado-VT repo used:

```
[cleber@localhost avocado-vt]$ git show 
commit f7df28147306e45ca903b4da676c154cae329cdf
Merge: cf857b1 8a7f3db
Author: Lucas Meneghel Rodrigues <lmr@scylladb.com>
Date:   Wed Dec 23 14:08:50 2015 -0200

    Merge pull request #296 from nflondo/suse-guest-os
    
    Request to add OpenSUSE Leap 42.1.x86_64.cfg and its xml file for unattended install
```

Running Avocado after installing Avocado and Avocado-vt with `$ python setup.py install`:

```
[cleber@localhost ~]$ avocado 
Failed to load plugin from module "avocado_vt.plugins.vt_list": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
Failed to load plugin from module "avocado_vt.plugins.vt": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
usage: avocado [-h] [-v] [--config CONFIG_FILE]
               
               {exec-path,run,config,list,multiplex,plugins,sysinfo,distro,vt-bootstrap}
               ...
avocado: error: too few arguments
```

Bootstrapping:

```
[cleber@localhost ~]$ avocado vt-bootstrap 
Failed to load plugin from module "avocado_vt.plugins.vt_list": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
Failed to load plugin from module "avocado_vt.plugins.vt": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
11:48:00 INFO | qemu test config helper
11:48:00 INFO | 
11:48:00 INFO | 1 - Updating all test providers
11:48:00 DEBUG| Creating directory /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-libvirt for git repo http://github.com/autotest/tp-libvirt.git
11:48:00 DEBUG| Initializing new git repo at /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-libvirt for receiving git repo http://github.com/autotest/tp-libvirt.git
11:48:00 INFO | Fetching git [REP 'http://github.com/autotest/tp-libvirt.git' BRANCH 'master'] -> /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-libvirt
11:48:11 DEBUG| Checking out branch master
11:48:12 DEBUG| Specific commit not specified
11:48:12 INFO | git commit ID is 1cc80fbdc7571acbc705cfa6141b001914e94b30 (no tag found)
11:48:14 DEBUG| Creating directory /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu for git repo http://github.com/autotest/tp-qemu.git
11:48:14 DEBUG| Initializing new git repo at /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu for receiving git repo http://github.com/autotest/tp-qemu.git
11:48:14 INFO | Fetching git [REP 'http://github.com/autotest/tp-qemu.git' BRANCH 'master'] -> /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu
11:48:27 DEBUG| Checking out branch master
11:48:27 DEBUG| Specific commit not specified
11:48:27 INFO | git commit ID is 8b3bfe9b3cdd29e2419b7dc7b97549d1d43c549b (no tag found)
11:48:29 DEBUG| Creating directory /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice for git repo https://github.com/spiceqa/tp-spice.git
11:48:29 DEBUG| Initializing new git repo at /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice for receiving git repo https://github.com/spiceqa/tp-spice.git
11:48:29 INFO | Fetching git [REP 'https://github.com/spiceqa/tp-spice.git' BRANCH 'master'] -> /home/cleber/avocado/data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice
11:48:35 DEBUG| Checking out branch master
11:48:35 DEBUG| Specific commit not specified
11:48:35 INFO | git commit ID is 511470925c217c9372d004eed14158d27e9f55cb (no tag found)
11:48:36 INFO | 
11:48:36 INFO | 2 - Checking the mandatory programs and headers
11:48:36 INFO | /bin/7za OK
11:48:36 INFO | /sbin/tcpdump OK
11:48:36 INFO | /bin/nc OK
11:48:36 INFO | /sbin/ip OK
11:48:36 INFO | /sbin/arping OK
11:48:36 INFO | /bin/gcc OK
11:48:36 INFO | /usr/include/python2.7/Python.h OK
11:48:36 INFO | /usr/include/asm/socket.h OK
11:48:36 INFO | /usr/include/asm/types.h OK
11:48:36 INFO | /usr/include/asm/unistd.h OK
11:48:36 INFO | 
11:48:36 INFO | 3 - Checking the recommended programs
11:48:36 INFO | /usr/libexec/qemu-kvm OK
11:48:36 INFO | /bin/qemu-img OK
11:48:36 INFO | /bin/qemu-io OK
11:48:36 INFO | 
11:48:36 INFO | 4 - Verifying directories
11:48:36 DEBUG| Creating /home/cleber/avocado/data/avocado-vt/images
11:48:36 DEBUG| Creating /home/cleber/avocado/data/avocado-vt/isos
11:48:36 DEBUG| Creating /home/cleber/avocado/data/avocado-vt/steps_data
11:48:36 DEBUG| Creating /home/cleber/avocado/data/avocado-vt/gpg
11:48:36 INFO | Syncing backend dirs /usr/share/avocado-plugins-vt/backends -> /home/cleber/avocado/data/avocado-vt/backends
11:48:36 INFO | 
11:48:36 INFO | 5 - Generating config set
11:48:36 DEBUG| Creating config file /home/cleber/avocado/data/avocado-vt/backends/qemu/cfg/base.cfg from sample
11:48:36 DEBUG| Creating config file /home/cleber/avocado/data/avocado-vt/backends/qemu/cfg/cdkeys.cfg from sample
11:48:36 DEBUG| Creating config file /home/cleber/avocado/data/avocado-vt/backends/qemu/cfg/guest-hw.cfg from sample
11:48:36 DEBUG| Creating config file /home/cleber/avocado/data/avocado-vt/backends/qemu/cfg/host-kernel-base.cfg from sample
11:48:36 DEBUG| Creating config file /home/cleber/avocado/data/avocado-vt/backends/qemu/cfg/machines.cfg from sample
11:48:36 DEBUG| Creating config file /home/cleber/avocado/data/avocado-vt/backends/qemu/cfg/virtio-win.cfg from sample
11:48:36 DEBUG| Config file /home/cleber/avocado/data/avocado-vt/backends/qemu/cfg/subtests.cfg auto generated from subtest samples
11:48:36 DEBUG| Config file /home/cleber/avocado/data/avocado-vt/backends/qemu/cfg/guest-os.cfg auto generated from guest OS samples
11:48:36 INFO | 
11:48:36 INFO | 6 - Verifying (and possibly downloading) guest image
11:48:37 INFO | Verifying expected SHA1 sum from http://assets-avocadoproject.rhcloud.com/static/SHA1SUM_JEOS21
11:48:37 INFO | Expected SHA1 sum: 177468b8e5fcb7b9c5982a6bc21ff45df6d80b2f
11:48:37 WARNI| File /home/cleber/avocado/data/avocado-vt/images/jeos-21-64.qcow2.7z not found
Would you like to download it from http://assets-avocadoproject.rhcloud.com/static/jeos-21-64.qcow2.7z? (y/n) y
11:48:41 INFO | Downloading jeos-21-64.qcow2.7z, 201.37 MB to /home/cleber/avocado/data/avocado-vt/images
Downloading JeOS 21 x86_64: [===============================================] 100%11:50:41 DEBUG| Uncompressing /home/cleber/avocado/data/avocado-vt/images/jeos-21-64.qcow2.7z -> /home/cleber/avocado/data/avocado-vt/images/jeos-21-64.qcow2
11:50:56 INFO | 
11:50:56 INFO | 7 - Checking for modules kvm, kvm-intel
11:50:56 DEBUG| Module kvm loaded
11:50:56 DEBUG| Module kvm-intel loaded
11:50:56 INFO | 
11:50:56 INFO | 8 - If you wish, you may take a look at the online docs for more info
11:50:56 INFO | 
11:50:56 INFO | http://avocado-vt.readthedocs.org/
```

Listing Avocado-VT tests:

```
[cleber@localhost ~]$ avocado list | grep 'boot$'
VT           type_specific.io-github-autotest-qemu.block_stream.when_reboot
VT           type_specific.io-github-autotest-qemu.balloon_check.balloon_evict.balloon-reboot
VT           type_specific.io-github-autotest-qemu.balloon_check.balloon_enlarge.balloon-reboot
VT           type_specific.io-github-autotest-qemu.pci_hotplug.hotplug_block.blk_virtio_blk.with_reboot
VT           type_specific.io-github-autotest-qemu.pci_hotplug.hotplug_block.blk_scsi.with_reboot
VT           type_specific.io-github-autotest-qemu.pci_hotplug.hotplug_block.blk_virtio_scsi.with_reboot
VT           type_specific.io-github-autotest-qemu.pci_hotplug.hotplug_nic.nic_rtl8139.with_reboot
VT           type_specific.io-github-autotest-qemu.pci_hotplug.hotplug_nic.nic_virtio_net.with_reboot
VT           type_specific.io-github-autotest-qemu.pci_hotplug.hotplug_nic.nic_e1000.with_reboot
VT           type_specific.io-github-autotest-qemu.gluster.gluster_boot_snap_boot
VT           type_specific.io-github-autotest-qemu.drive_mirror.with_reboot
VT           type_specific.io-github-autotest-qemu.system_reset_during_boot
VT           type_specific.io-github-autotest-qemu.live_snapshot.with_reboot
VT           io-github-autotest-qemu.boot
VT           io-github-autotest-qemu.stress_boot
VT           io-github-autotest-qemu.timedrift.with_pvclock.shared_ntp_date.date.with_reboot
VT           io-github-autotest-qemu.reboot
```

Running a boot test:

```
[cleber@localhost ~]$ avocado run io-github-autotest-qemu.boot 
JOB ID     : 8bffc449ac76ac3b95902f2aff4e62f5aa77f40e
JOB LOG    : /home/cleber/avocado/job-results/job-2015-12-23T11.52-8bffc44/job.log
TESTS      : 1
 (1/1) io-github-autotest-qemu.boot: PASS (56.14 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /home/cleber/avocado/job-results/job-2015-12-23T11.52-8bffc44/html/results.html
TIME       : 56.14 s
```

@rbian sorry but I can not reproduce your failures.

**Comment by clebergnu** [comment]
@rbian can you try again with the commits mentioned on my previous comment? If you manage to reproduce it yet again please re-open this issue.

**Comment by rbian** [comment]
Thanks @clebergnu . I find out the problem. The package version of stevedore is not correct on my system. After reinstallanation by pip, the problem goes away. 
stevedore version by yum: python-stevedore.noarch 0:0.14-1.el7
by pip: stevedore-1.10.0-py2.py3-none-any.whl

**Comment by PandaWei** [comment]
Hello, guys,

I want to run avocado-vt from sources, not by installing.
I put both avocado and avocado-vt under the the same directory,
And then,
run '/usr/bin/python setup.py develop --user' at avocado-vt directory.
run 'make link' at avocado directory.

But I‘ve had some problem like below,
[root@localhost avocado]# scripts/avocado plugins
Failed to load plugin from module "avocado_vt.plugins.vt_list": IOError(2, 'No such file or directory')
Failed to load plugin from module "avocado_vt.plugins.vt": IOError(2, 'No such file or directory')
Plugins that add new commands (avocado.plugins.cli.cmd):
vt-bootstrap Avocado VT - implements the 'vt-bootstrap' subcommand
exec-path    Returns path to avocado bash libraries and exits.
run          Run one or more tests (native test, test alias, binary or script)
............................................................................

Do i missed something?
Or it may be related to stevedore version.

[root@localhost avocado]# rpm -qa | grep stevedore
python-stevedore-0.14-1.el7.noarch
[root@localhost avocado]# pip search stevedore
stevedore (1.10.0)  - Manage dynamic plugins for Python applications
  INSTALLED: 1.12.0
  LATEST:    1.10.0

**Comment by rbian** [comment]
@PandaWei , After the installation, did you try the command "avocado plugins" directly? what's the output?

**Comment by PandaWei** [comment]
After running 'make install' for avocado, The ouput is the same as above.
[root@localhost ~]# avocado plugins
Failed to load plugin from module "avocado_vt.plugins.vt_list": IOError(2, 'No such file or directory')
Failed to load plugin from module "avocado_vt.plugins.vt": IOError(2, 'No such file or directory')
Plugins that add new commands (avocado.plugins.cli.cmd):
vt-bootstrap Avocado VT - implements the 'vt-bootstrap' subcommand
exec-path    Returns path to avocado bash libraries and exits.
run          Run one or more tests (native test, test alias, binary or script)
sysinfo      Collect system information
list         List available tests
...................

**Comment by rbian** [comment]
I think you'd better upgrade stevedore version first.
