### ISSUE TITLE
Logging line breaks broken for next runner + Avocado VT as of fc0ca12bef

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#3106]
@richtja have you seen something like this recently? I moved from the merge commit for the shiny new VT runner feature to the recent master branches for Avocado+VT but all my line breaks are no longer there:

```
file_transfer_client = scp2021-06-21 15:36:11,082 utils            L0167 DEBUG|     file_transfer_port = 222021-06-21 15:36:11,082 utils            L0167 DEBUG|     firefox_version = 68.11.02021-06-21 15:36:11,082 utils            L0167 DEBUG|     flexible_nic_index = no2021-06-21 15:36:11,082 utils            L0167 DEBUG|     get_mode = ra2021-06-21 15:36:11,082 utils            L0167 DEBUG|     get_state = customize2021-06-21 15:36:11,082 utils            L0167 DEBUG|     get_type = off2021-06-21 15:36:11,082 utils            L0167 DEBUG|     grub_file = /boot/grub/grub.conf2021-06-21 15:36:11,083 utils            L0167 DEBUG|     guest_autotest_verbosity = no2021-06-21 15:36:11,083 utils            L0167 DEBUG|     guest_port_remote_shell = 222021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_additional_ports = 14372021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_b0 = 192.168.21.2542021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_b1 = 10.21.0.2542021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_dhcp_authoritative = no2021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_dhcp_blacklist = br02021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_dhcp_service = yes2021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_dhcp_service_b0 = no2021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_dns_authoritative = no2021-06-21 15:36:11,083 utils            L0167 DEBUG|     host_dns_blacklist = br02021-06-21 15:36:11,083 utils            L0167 DEBUG|  
```

**Comment by richtja** [comment]
Hi @pevogam thanks for the report, I think I know where is the problem I will send the fix.

**Comment by pevogam** [comment]
@richtja I guess this can now be closed and I could report the following in a separate issue but was wondering if it could be related in any way: I am getting some string types written as bytes in the log files (and thus errors out). If I do the following fix on the Avocado side:
```diff
         def _save_to_file(file_name, mode):
+            final_buff = buff
+            if "b" in mode and isinstance(final_buff, str):
+                # TODO: some stderr output of Avocado VT is passed here as string
+                final_buff = bytes(buff, encoding='utf8')
             with open(file_name, mode) as fp:
-                fp.write(buff)
+                fp.write(final_buff)
```
then everything works but for some reason from Avocado VT (here) I am getting a mode with binary flag and a string `buff` variable. Could this be related in any way?

**Comment by richtja** [comment]
@pevogam from what you are saying it looks like is related. Can you give me an example, where this is happening, because I am not able to reproduce it. 

Also, I hope that these problems will end when we will be using generic messaging in avocado-vt runner, so if you want you can look at [#4699](https://github.com/avocado-framework/avocado/pull/4699) on avocado side, it's about helper messaging methods for runners.

**Comment by pevogam** [comment]
Hi @richtja, from my full use in the last two days I didn't have any further trouble, I guess this could have indeed been fixed by your PR corresponding to this issue. Good job!
