### ISSUE TITLE
`TestSkipError` is handled with an ERROR status by the parallel VT runner

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#3107]
I think currently there is no support for SKIP test statuses so I am adding this issue here to trace progress on this for the future.

Mentioning @richtja, @beraldoleal, @willianrampazzo, @clebergnu just in case anybody creates a duplicate issue or they don't follow up on Avocado VT and as this is probably also a limitation in general Avocado.

**Comment by pevogam** [comment]
I can also confirm no support for WARN test statuses too as well as FAIL, we only get PASS or ERROR so far.

**Comment by richtja** [comment]
Reopening because of problems with status details. See https://github.com/avocado-framework/avocado-vt/pull/3201#issuecomment-912659714

**Comment by pevogam** [comment]
Thanks for reopening @richtja, let me know when you need some testing and reviewing regarding this.
