### ISSUE TITLE
Re-enable the travis-ci check

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/avocado-vt#3114]
Since June 15th, 2021, the building on travis-ci.org is ceased. Therefore a migration to travis-ci.com is required if we want to continue the use.

@clebergnu, shall we re-enable the travis-ci check for avocado-vt, or is there any concern about that?

**Comment by chunfuwen** [comment]
It sounds like avocado itself is migrated to travis.com, not sure how to migrate it from travis.org to travis.com

**Comment by luckyh** [comment]
> It sounds like avocado itself is migrated to travis.com, not sure how to migrate it from travis.org to travis.com

@chunfuwen yes, I can see that in [this page](https://www.travis-ci.com/organizations/avocado-framework/repositories), and avocado-vt is indeed not migrated yet, so I think it's better to confirm it here.

**Comment by chunfuwen** [comment]
<ana> chunfu, avocado-vt migrated, I just triggered a build for master: https://www.travis-ci.com/github/avocado-framework/avocado-vt

avocado-vt travis CI on travis.com can be triggered now

**Comment by luckyh** [comment]
> ```
> <ana> chunfu, avocado-vt migrated, I just triggered a build for master: https://www.travis-ci.com/github/avocado-framework/avocado-vt
> 
> avocado-vt travis CI on travis.com can be triggered now
> ```

@chunfuwen @ana thank you!

Mark as resolved.
