### ISSUE TITLE
Reuse the avocado logger

### ISSUE THREAD

**Issue by PaulYuuu** [avocado-framework/avocado-vt#3169]
This is a continuation of the discussion on https://github.com/avocado-framework/avocado/issues/4797

After https://github.com/avocado-framework/avocado/pull/4787 has been introduced, the VT runner will print excessive outputs.
```
INFO | Creating test configuration file '/root/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg'
INFO | Assigning vcpu num '4'
INFO | Assigning memory size '7168'
INFO | Start to run test
INFO:root:Config provided, ignoring option --vt-guest-os
INFO:root:Config provided, ignoring option --vt-arch or config vt.common.arch
INFO:root:Config provided, ignoring option --vt-machine-type or config vt.common.machine_type
INFO:root:Config provided and no option --vt-qemu-img or config vt.qemu.qemu_img set. Not trying to automatically set qemu bin
INFO:root:Config provided, ignoring config vt.qemu.nettype
INFO:root:Config provided, ignoring monitor setting
INFO:root:Config provided, ignoring config vt.qemu.smp
INFO:root:Config provided, ignoring config vt.qemu.image_type
INFO:root:Config provided, ignoring config vt.qemu.nic_model
INFO:root:Config provided, ignoring config vt.qemu.disk_bus
INFO:root:Config provided, ignoring config vt.qemu.vhost
INFO:root:Config provided, ignoring config vt.qemu.sandbox
JOB ID     : 41847374093671a4b3b5e6c4bde8b520ef09d3d5
JOB LOG    : /root/avocado/job-results/job-2021-08-06T08.55-4184737/job.log
 (1/1) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.boot.s390-virtio:  INFO:root:Avocado-VT 'unknown'
DEBUG:root:Searching for test modules that match 'type = boot' and 'provider = io-github-autotest-qemu' on this cartesian dict
DEBUG:root:Found subtest module /root/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/boot.py
WARNING:root:Creating new, empty env file
```

I tried to fix it so I add `logging.root = logging.getLogger('avocado')` in loader.py.
```diff
--- a/avocado_vt/loader.py
+++ b/avocado_vt/loader.py
@@ -34,7 +34,7 @@ from .test import VirtTest
 
 
 LOG = logging.getLogger("avocado.app")
-
+logging.root = logging.getLogger('avocado')
 
 def guest_listing(config, guest_name_parser=None):
     """
```

This change works for me, but I am not sure if the change in this place is correct.
```
INFO | Creating test configuration file '/root/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg'
INFO | Assigning vcpu num '4'
INFO | Assigning memory size '7168'
INFO | Start to run test
JOB ID     : ab2653657449d93974eeb3b11135c195ef400895
JOB LOG    : /root/avocado/job-results/job-2021-08-06T08.56-ab26536/job.log
 (1/1) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.boot.s390-virtio: PASS (25.56 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

Hello @beraldoleal @pevogam @luckyh , I think we should reuse the avocado logger indeed, so I invite you into this thread, please correct me if I mistake something, I am also glad to see if someone can help address the problem directly:smiley_cat: 

Thank you all in advance.

**Comment by luckyh** [comment]
> Hello @beraldoleal @pevogam @luckyh , I think we should reuse the avocado logger indeed, so I invite you into this thread, please correct me if I mistake something, I am also glad to see if someone can help address the problem directlysmiley_cat

@PaulYuuu looks good to me for having the monkey patch like this to bypass the issue, and it looks like we can move the fix to `avocado_vt.test.VirtTest.setUp` to limit the effective scope to only VT tests.

**Comment by pevogam** [comment]
Hi @PaulYuuu I did a similar patch offline but I read on some forums that it is not recommended to override the root logger in this way since lots of other constructs link to it and make implicit use of it. Nevertheless, it worked as a quick fix to make the UI usable again so I guess we have to consider it as an option.

Regarding the general issue of the recent logging changes, have you checked your `debug.log` files and validated that all of the previous test output is there (no suprising output from other modules and no missing output)? This fix will solve the host-side logging beyond the tests for all used modules and logging messages, I was just wondering if you also have trouble within the test logging collected by the VT runner.

**Comment by PaulYuuu** [comment]
> Hi @PaulYuuu I did a similar patch offline but I read on some forums that it is not recommended to override the root logger in this way since lots of other constructs link to it and make implicit use of it. Nevertheless, it worked as a quick fix to make the UI usable again so I guess we have to consider it as an option.
> 
> Regarding the general issue of the recent logging changes, have you checked your `debug.log` files and validated that all of the previous test output is there (no suprising output from other modules and no missing output)? This fix will solve the host-side logging beyond the tests for all used modules and logging messages, I was just wondering if you also have trouble within the test logging collected by the VT runner.

Yep, I probably took a look, the `debug.log`/`job.log` looks the same as before I guess, I can get some output I want to see, the vt bootstrap also looks good. Before adding this line, some outputs are duplicated of the debug.log, but after that, everything seems to be normal.

**Comment by PaulYuuu** [comment]
> > Hello @beraldoleal @pevogam @luckyh , I think we should reuse the avocado logger indeed, so I invite you into this thread, please correct me if I mistake something, I am also glad to see if someone can help address the problem directlysmiley_cat
> 
> @PaulYuuu looks good to me for having the monkey patch like this to bypass the issue, and it looks like we can move the fix to `avocado_vt.test.VirtTest.setUp` to limit the effective scope to only VT tests.

@luckyh I have tried it, but this change will lose some messages in `debug.log`/`job.log`, so I think another place that can be modified may be under `VirtTestLoader`. You can see all output was lost during the period from 02:00:54 to 02:16:28.
```
02:00:54 DEBUG| [stdout]     "virtual-size": 21474836480,
02:00:54 DEBUG| [stdout]     "filename": "/home/kvm_autotest_root/images/image.qcow2",
02:00:54 DEBUG| [stdout]     "cluster-size": 65536,
02:00:54 DEBUG| [stdout]     "format": "qcow2",
02:00:54 DEBUG| [stdout]     "actual-size": 200704,
02:00:54 DEBUG| [stdout]     "format-specific": {
02:00:54 DEBUG| [stdout]         "type": "qcow2",
02:00:54 DEBUG| [stdout]         "data": {
02:00:54 DEBUG| [stdout]             "compat": "1.1",
02:00:54 DEBUG| [stdout]             "compression-type": "zlib",
02:00:54 DEBUG| [stdout]             "lazy-refcounts": false,
02:00:54 DEBUG| [stdout]             "refcount-bits": 16,
02:00:54 DEBUG| [stdout]             "corrupt": false,
02:00:54 DEBUG| [stdout]             "extended-l2": false
02:00:54 DEBUG| [stdout]         }
02:00:54 DEBUG| [stdout]     },
02:00:54 DEBUG| [stdout]     "dirty-flag": false
02:00:54 DEBUG| [stdout] }
02:16:28 INFO | Running '/usr/bin/qemu-img info -U /home/kvm_autotest_root/images/image.qcow2 --output=human'
02:16:28 DEBUG| [stdout] image: /home/kvm_autotest_root/images/rhel850-aarch64-virtio-scsi.qcow2
02:16:28 INFO | Command '/usr/bin/qemu-img info -U /home/kvm_autotest_root/images/image.qcow2 --output=human' finished with 0 after 0.005646861000059289s
02:16:28 DEBUG| [stdout] file format: qcow2
02:16:28 DEBUG| [stdout] virtual size: 20 GiB (21474836480 bytes)
02:16:28 DEBUG| [stdout] disk size: 4.75 GiB
```

**Comment by beraldoleal** [comment]
> This is a continuation of the discussion on [avocado-framework/avocado#4797](https://github.com/avocado-framework/avocado/issues/4797)
> 
> After [avocado-framework/avocado#4787](https://github.com/avocado-framework/avocado/pull/4787) has been introduced, the VT runner will print excessive outputs.
> 
> ```
> INFO | Creating test configuration file '/root/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg'
> INFO | Assigning vcpu num '4'
> INFO | Assigning memory size '7168'
> INFO | Start to run test
> INFO:root:Config provided, ignoring option --vt-guest-os
> INFO:root:Config provided, ignoring option --vt-arch or config vt.common.arch
> INFO:root:Config provided, ignoring option --vt-machine-type or config vt.common.machine_type
> INFO:root:Config provided and no option --vt-qemu-img or config vt.qemu.qemu_img set. Not trying to automatically set qemu bin
> INFO:root:Config provided, ignoring config vt.qemu.nettype
> INFO:root:Config provided, ignoring monitor setting
> INFO:root:Config provided, ignoring config vt.qemu.smp
> INFO:root:Config provided, ignoring config vt.qemu.image_type
> INFO:root:Config provided, ignoring config vt.qemu.nic_model
> INFO:root:Config provided, ignoring config vt.qemu.disk_bus
> INFO:root:Config provided, ignoring config vt.qemu.vhost
> INFO:root:Config provided, ignoring config vt.qemu.sandbox
> JOB ID     : 41847374093671a4b3b5e6c4bde8b520ef09d3d5
> JOB LOG    : /root/avocado/job-results/job-2021-08-06T08.55-4184737/job.log
>  (1/1) Host_RHEL.m8.u5.product_av.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.5.0.s390x.io-github-autotest-qemu.boot.s390-virtio:  INFO:root:Avocado-VT 'unknown'
> DEBUG:root:Searching for test modules that match 'type = boot' and 'provider = io-github-autotest-qemu' on this cartesian dict
> DEBUG:root:Found subtest module /root/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/boot.py
> WARNING:root:Creating new, empty env file
> ```
> 
> I tried to fix it so I add `logging.root = logging.getLogger('avocado')` in loader.py.

As pointed by @pevogam already, this is not recommended. You are replacing the root logger and not recovering the original back after the usage.

Seems to me that those lines are produced by `avocado_vt/options.py'  that is logging directly to the root logging.

IIUC, I would recommend something like this:

```diff
diff --git a/avocado_vt/options.py b/avocado_vt/options.py
index 9300e554..2e6ad980 100644
--- a/avocado_vt/options.py
+++ b/avocado_vt/options.py
@@ -34,6 +34,9 @@ from virttest.standalone_test import SUPPORTED_NIC_MODELS
 from virttest.standalone_test import SUPPORTED_TEST_TYPES
 
 
+LOG = logging.getLogger('avocado.vt.option')
+
+
 class VirtTestOptionsProcess(object):
 
     """
@@ -124,8 +127,8 @@ class VirtTestOptionsProcess(object):
                             'config vt.qemu.qemu_bin')
         if (get_opt(self.config, 'vt.config') and
                 get_opt(self.config, 'vt.qemu.qemu_bin') is None):
-            logging.info("Config provided and no %s set. Not trying "
-                         "to automatically set qemu bin.", qemu_bin_setting)
+            LOG.info("Config provided and no %s set. Not trying "
+                     "to automatically set qemu bin.", qemu_bin_setting)
         else:
             (qemu_bin_path, qemu_img_path, qemu_io_path,
              qemu_dst_bin_path) = standalone_test.find_default_qemu_paths(
@@ -146,8 +149,8 @@ class VirtTestOptionsProcess(object):
                             'config vt.qemu.qemu_img')
         if (get_opt(self.config, 'vt.config') and
                 get_opt(self.config, 'vt.qemu.bin') is None):
-            logging.info("Config provided and no %s set. Not trying "
-                         "to automatically set qemu bin", qemu_img_setting)
+            LOG.info("Config provided and no %s set. Not trying "
+                     "to automatically set qemu bin", qemu_img_setting)
         else:
             (_, qemu_img_path,
              _, _) = standalone_test.find_default_qemu_paths(
@@ -191,7 +194,7 @@ class VirtTestOptionsProcess(object):
             elif get_opt(self.config, 'vt.common.nettype') == 'user':
                 self.cartesian_parser.assign("nettype", "user")
         else:
-            logging.info("Config provided, ignoring %s", nettype_setting)
+            LOG.info("Config provided, ignoring %s", nettype_setting)
 
     def _process_monitor(self):
         if not get_opt(self.config, 'vt.config'):
@@ -202,7 +205,7 @@ class VirtTestOptionsProcess(object):
             elif get_opt(self.config, 'vt.qemu.monitor') == 'human':
                 self.cartesian_parser.assign("monitor_type", "human")
         else:
-            logging.info("Config provided, ignoring monitor setting")
+            LOG.info("Config provided, ignoring monitor setting")
 
     def _process_smp(self):
         smp_setting = 'config vt.qemu.smp'
@@ -220,12 +223,12 @@ class VirtTestOptionsProcess(object):
                     raise ValueError("Invalid %s '%s'. Valid value: (1, 2, "
                                      "or integer)" % get_opt(self.config, 'vt.qemu.smp'))
         else:
-            logging.info("Config provided, ignoring %s", smp_setting)
+            LOG.info("Config provided, ignoring %s", smp_setting)
 
     def _process_arch(self):
         if get_opt(self.config, 'vt.config'):
             arch_setting = "option --vt-arch or config vt.common.arch"
-            logging.info("Config provided, ignoring %s", arch_setting)
+            LOG.info("Config provided, ignoring %s", arch_setting)
             return
 
         arch = get_opt(self.config, 'vt.common.arch')
@@ -247,7 +250,7 @@ class VirtTestOptionsProcess(object):
                 self.cartesian_parser.only_filter(get_opt(self.config,
                                                           'vt.common.machine_type'))
         else:
-            logging.info("Config provided, ignoring %s", machine_type_setting)
+            LOG.info("Config provided, ignoring %s", machine_type_setting)
 
     def _process_image_type(self):
         image_type_setting = 'config vt.qemu.image_type'
@@ -260,7 +263,7 @@ class VirtTestOptionsProcess(object):
                 self.cartesian_parser.assign("image_format",
                                              get_opt(self.config, 'vt.qemu.image_type'))
         else:
-            logging.info("Config provided, ignoring %s", image_type_setting)
+            LOG.info("Config provided, ignoring %s", image_type_setting)
 
     def _process_nic_model(self):
         nic_model_setting = 'config vt.qemu.nic_model'
@@ -272,7 +275,7 @@ class VirtTestOptionsProcess(object):
                 self.cartesian_parser.assign(
                     "nic_model", get_opt(self.config, 'vt.qemu.nic_model'))
         else:
-            logging.info("Config provided, ignoring %s", nic_model_setting)
+            LOG.info("Config provided, ignoring %s", nic_model_setting)
 
     def _process_disk_buses(self):
         disk_bus_setting = 'config vt.qemu.disk_bus'
@@ -285,7 +288,7 @@ class VirtTestOptionsProcess(object):
                                   get_opt(self.config, 'vt.qemu.disk_bus'),
                                   SUPPORTED_DISK_BUSES))
         else:
-            logging.info("Config provided, ignoring %s", disk_bus_setting)
+            LOG.info("Config provided, ignoring %s", disk_bus_setting)
 
     def _process_vhost(self):
         nettype_setting = 'config vt.qemu.nettype'
@@ -306,7 +309,7 @@ class VirtTestOptionsProcess(object):
                                         vhost_setting,
                                         get_opt(self.config, 'vt.qemu.vhost')))
         else:
-            logging.info("Config provided, ignoring %s", vhost_setting)
+            LOG.info("Config provided, ignoring %s", vhost_setting)
 
     def _process_qemu_sandbox(self):
         sandbox_setting = 'config vt.qemu.sandbox'
@@ -314,7 +317,7 @@ class VirtTestOptionsProcess(object):
             if get_opt(self.config, 'vt.qemu.sandbox') == "off":
                 self.cartesian_parser.assign("qemu_sandbox", "off")
         else:
-            logging.info("Config provided, ignoring %s", sandbox_setting)
+            LOG.info("Config provided, ignoring %s", sandbox_setting)
 
     def _process_qemu_defconfig(self):
         defconfig_setting = 'config vt.qemu.sandbox'
@@ -322,7 +325,7 @@ class VirtTestOptionsProcess(object):
             if get_opt(self.config, 'vt.qemu.defconfig') == "no":
                 self.cartesian_parser.assign("defconfig", "no")
         else:
-            logging.info("Config provided, ignoring %s", defconfig_setting)
+            LOG.info("Config provided, ignoring %s", defconfig_setting)
 
     def _process_malloc_perturb(self):
         self.cartesian_parser.assign("malloc_perturb",
@@ -375,7 +378,7 @@ class VirtTestOptionsProcess(object):
         guest_os_setting = 'option --vt-guest-os'
 
         if get_opt(self.config, 'vt.type') == 'spice':
-            logging.info("Ignoring predefined OS: %s", guest_os_setting)
+            LOG.info("Ignoring predefined OS: %s", guest_os_setting)
             return
 
         if not get_opt(self.config, 'vt.config'):
@@ -390,7 +393,7 @@ class VirtTestOptionsProcess(object):
             self.cartesian_parser.only_filter(
                 get_opt(self.config, 'vt.guest_os') or defaults.DEFAULT_GUEST_OS)
         else:
-            logging.info("Config provided, ignoring %s", guest_os_setting)
+            LOG.info("Config provided, ignoring %s", guest_os_setting)
 
     def _process_restart_vm(self):
         if not get_opt(self.config, 'vt.config'):
```

> 
> Hello @beraldoleal @pevogam @luckyh , I think we should reuse the avocado logger indeed, so I invite you into this thread, please correct me if I mistake something, I am also glad to see if someone can help address the problem directlysmiley_cat

Thanks for tagging me here.

**Comment by PaulYuuu** [comment]
Hi @beraldoleal , thank you for providing the solution above, and it works for me on my python3.6 environment indeed. 

Unfortunately, as I mentioned at #3179, python3.9 will also print excessive output with this change, so I will investigate the differences between python3.6 and python3.9. Anyway, thank you all guys here.
