### ISSUE TITLE
avocado-vt calls register_plugin, which is probably deprecated

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado-vt#322]
Hi @clebergnu, I noticed an ignored traceback and don't have time to investigate what is needed. You ported avocado-vt to the new plugins structure, would you please take a look at this?

When running "DEBUG=y avocado run passtest" I see:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 255, in _invoke_one_plugin
    response_callback(func(e, *args, **kwds))
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 229, in _call_extension_method
    return getattr(extension.obj, method_name)(*args, **kwds)
  File "/home/medic/Work/Projekty/avocado/avocado-vt/avocado_vt/plugins/vt.py", line 1237, in run
    loader.register_plugin(VirtTestLoader)
AttributeError: 'module' object has no attribute 'register_plugin'
```

I can't guarantee you can see the traceback, I'm in the middle of the logging refactor so I see things which are not always visible :smile:. Anyway I looked at the `vt.py` and it contains the `register_plugin` when other plugins don't call that.

**Comment by clebergnu** [comment]
@ldoktor this bug has been confirmed. Please take a look at the proposed fix (both on avocado-vt and avocado).

**Comment by lmr** [comment]
Closing this per 2a072da
