### ISSUE TITLE
About how does the usb_by_params match the configuration

### ISSUE THREAD

**Issue by bgartzi** [avocado-framework/avocado-vt#3351]
When working on some usb-related bug I had to check configuration files regarding usb devices, and there was something that it was quite confusing to me.

The base.cfg file sets up the following configuration:
https://github.com/avocado-framework/avocado-vt/blob/d10af686d73b08a9561b353d04eb89dbde0c4c2c/virttest/shared/cfg/base.cfg#L137-L144
Okay, so a usb-tablet device should be attached to the vm, whose id should be usb-tablet1. As I understood the first time I was reading the cfg, its bus should be set to `usb1.0` as the `usb_bus` variable sets.

However, while the qemu command is built, the `usb_by_params` will set the device's bus as the one given in the variable `bus_<suffix>` i.e. `bus_tablet1`, and will just ignore the value hold by the `usb_bus` variable:
https://github.com/avocado-framework/avocado-vt/blob/d10af686d73b08a9561b353d04eb89dbde0c4c2c/virttest/qemu_devices/qcontainer.py#L1656-L1662

I checked the code and it seems that no variable is reading from the `usb_bus` nor the `bus` config parameter when regarding to usb device configuration in avocado-vt. There are some cases in tp-qemu in which the `usb_bus` is set in the configuration and then read from the test case itself. There are also some cases in which the `usb_port` is set, but I'm not sure whether it is being correctly read when configuring the target device or not.

Due to the way in which ports and buses for other kind (e.g. `drive_bus_...`, ...) are set, I was thinking that changing the lines from qcontainer.py that I already referenced would help to read from the usb configuration that is being set in different files.  However, this could affect other test providers.

I'm opening the issue so it can be discussed.

**Comment by luckyh** [comment]
> Due to the way in which ports and buses for other kind (e.g. `drive_bus_...`, ...) are set, I was thinking that changing the lines from qcontainer.py that I already referenced would help to read from the usb configuration that is being set in different files. 

This sounds fairly reasonable to me. After digging into the commit history (https://github.com/avocado-framework/avocado-vt/commit/c847833a1f15085eb6a2bf0a52ed71d58748962f, https://github.com/avocado-framework/avocado-vt/commit/4c5a4f74ce82afd733171907cb2e043ff4be6fc2) I intended to understand the mismatch of the parameter name between the configuration and the script as a mistake, and to me `usb_bus` looks much better or else I would suggest using another name `usbdev_bus` for easily distinguishing the params of usb controllers and usb devices.

> However, this could affect other test providers.

Indeed, but fortunately we only need to consider on those ones based on `vt_type=qemu`, and thus from my point of view it would probably be okay to have this change.

Thanks!
