### ISSUE TITLE
data_dir.get_data_dir() return /root/avocado/data/avocado-vt on 92lts instead of /var/lib/avocado/data/avocado-vt, it will impact tp-libvirt largely

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#3355]
Issue description:
1) Compared with avocado 82lts, data_dir.get_data_dir() will return ~/avocado/data/avocado-vt  instead of fixed folder: /var/lib/avocado/data/avocado-vt
2) I can understand this may intended feature, but it does impact tp-libvirt largely
3) In tp-libvirt, we use data_dir.get_data_dir() as base_folder to create image, and attach it into VM
4) The issue is that  permission deny error will happen if attach image from /root/avocado/data/avocado-vt 
5)Here it is one typical example:
```
    [root@dell-per430-17 ~]# virsh attach-disk avocado-vt-vm1 /root/avocado/data/avocado-vt/test.img vdb  --live
    error: Failed to attach disk
    error: internal error: unable to execute QEMU command 'blockdev-add': Could not open '/root/avocado/data/avocado-vt/test.img': Permission denied
    
    [root@dell-per430-17 ~]# qemu-img create -f qcow2 /var/lib/test.img 10M
    Formatting '/var/lib/test.img', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=10485760 lazy_refcounts=off refcount_bits=16
    [root@dell-per430-17 ~]# virsh attach-disk avocado-vt-vm1 /var/lib/test.img vdb  --live
    Disk attached successfully
```

**Comment by chunfuwen** [comment]
@kylazhang 
@dzhengfy 
FYI

**Comment by dzhengfy** [comment]
@chunfuwen , The error you saw is due to libvirt have no permission to access /root because it is acting as qemu user. So we need to use another directory to storing our image as before. Jil has fixed it by providing customized configuration with our desired data_dir value. So this could be closed now.

**Comment by chunfuwen** [comment]
close it since those folder can be dynamically configured in avocado-vt/avocado_vt/conf.d/vt.con
