### ISSUE TITLE
[Errno 24] Too many open files: '/tmp/aexpect_R4ScLlsr/lock-server-running'

### ISSUE THREAD

**Issue by spottbat** [avocado-framework/avocado-vt#3560]
I am running 40VM and inside each VM I am running small test for 300 secs after in between the test I am getting this error.
I have to tried to increase ulimit -n but that does not help me.
This issue occurred always when I use more than 25VMs , for 20VMs it is running well.
I am launching all VMs on thread.
Appreciate any pointers on resolving this issue.

[stderr] Exception in thread
[stderr] Thread-20 (task)
[stderr] :
[stderr] Traceback (most recent call last):
[stderr]   File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
[stderr]
[stderr] self.run()
[stderr]
[stderr]   File "/usr/lib64/python3.10/threading.py", line 953, in run
[stderr]
[stderr] self._target(*self._args, **self._kwargs)
[stderr]
[stderr]   File "/home/avocado/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/cpu_val.py", line 95, in task
[stderr]
[stderr] vm.verify_dmesg()
[stderr]
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/virt_vm.py", line 533, in manage_session
[stderr]
[stderr] vm.session.close()
[stderr]
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/client.py", line 367, in close
[stderr]
[stderr] wait_for_lock(self.lock_server_running_filename)
[stderr]
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/shared.py", line 55, in wait_for_lock
[stderr]
[stderr] lock_fd = get_lock_fd(filename)
[stderr]
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/shared.py", line 26, in get_lock_fd
[stderr]
[stderr] lock_fd = os.open(filename, os.O_RDWR)
[stderr]
**[stderr] OSError
[stderr] :
[stderr] [Errno 24] Too many open files: '/tmp/aexpect_R4ScLlsr/lock-server-running'**
[stderr]
[stderr] Exception in thread
[stderr] Thread-28 (task)
[stderr] :
[stderr] Traceback (most recent call last):
[stderr]   File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
[stderr]   File "/usr/lib64/python3.10/threading.py", line 953, in run
[stderr]   File "/home/avocado/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/cpu_val.py", line 95, in task
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/virt_vm.py", line 533, in manage_session
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/client.py", line 365, in close
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/client.py", line 356, in kill
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/utils/process.py", line 75, in kill_process_tree
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/utils/process.py", line 73, in kill_process_tree
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/utils/process.py", line 21, in getoutput
[stderr]   File "/usr/lib64/python3.10/subprocess.py", line 835, in __init__
[stderr]   File "/usr/lib64/python3.10/subprocess.py", line 1625, in _get_handles
**[stderr] OSError
[stderr] :
[stderr] [Errno 24] Too many open files
[stderr]
[stdlog] 2022-11-09 15:03:40,575 avocado.virttest.env_process WARNI| [Errno 24] Too many open files (/usr/bin/virsh qemu-monitor-command FRVM6 --hmp --cmd 'info registers')**
[stderr] Exception in thread
[stderr] VmMonInfo
[stderr] :
[stderr] Traceback (most recent call last):
[stderr]   File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
[stderr]   File "/usr/lib64/python3.10/threading.py", line 953, in run
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/env_process.py", line 2108, in _store_vm_info
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/libvirt_vm.py", line 251, in is_alive
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/virsh.py", line 1427, in is_alive
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/virsh.py", line 1440, in is_dead
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/virsh.py", line 1181, in domstate
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/virsh.py", line 816, in command
[stderr]   File "/usr/local/lib/python3.10/site-packages/avocado/utils/process.py", line 1006, in run
[stderr]   File "/usr/local/lib/python3.10/site-packages/avocado/utils/process.py", line 938, in run
[stderr]   File "/usr/local/lib/python3.10/site-packages/avocado/utils/process.py", line 669, in _init_subprocess
[stderr]   File "/usr/local/lib/python3.10/site-packages/avocado/utils/process.py", line 660, in _init_subprocess
[stderr]   File "/usr/lib64/python3.10/subprocess.py", line 835, in __init__
[stderr]   File "/usr/lib64/python3.10/subprocess.py", line 1611, in _get_handles
[stderr] OSError
[stderr] :
[stderr] [Errno 24] Too many open files (/usr/bin/virsh -c 'qemu:///system' domstate FRVM7 )
[stderr]
[stderr] Exception in thread
[stderr] Thread-29 (task)
[stderr] :
[stderr] Traceback (most recent call last):
[stderr]   File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
[stderr]   File "/usr/lib64/python3.10/threading.py", line 953, in run
[stderr]   File "/home/avocado/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/cpu_val.py", line 95, in task
[stderr]   File "/usr/local/lib/python3.10/site-packages/virttest/virt_vm.py", line 533, in manage_session
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/client.py", line 365, in close
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/client.py", line 356, in kill
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/utils/process.py", line 75, in kill_process_tree
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/utils/process.py", line 73, in kill_process_tree
[stderr]   File "/usr/local/lib/python3.10/site-packages/aexpect/utils/process.py", line 21, in getoutput
[stderr]   File "/usr/lib64/python3.10/subprocess.py", line 835, in __init__
[stderr]   File "/usr/lib64/python3.10/subprocess.py", line 1625, in _get_handles

**Comment by luckyh** [comment]
Hi @spottbat , thanks for the issue reporting! Would you please check if [this fix](https://github.com/avocado-framework/aexpect/pull/97) has been applied to the aexpect package on your side?
