### ISSUE TITLE
travics ci failure due to loader module 

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado-vt#3591]
Refer to https://github.com/avocado-framework/avocado-vt/pull/3586/checks?check_run_id=10081035174
avocado-vt travis ci failed with below error message, and it failed when from avocado.core import loader.
Checking avocado source code, finding that loader.py is not under https://github.com/avocado-framework/avocado/tree/master/avocado/core, but reside under https://github.com/avocado-framework/avocado/blob/master/avocado/core/utils/loader.py.

Moreover, loader.py under https://github.com/avocado-framework/avocado/blob/master/avocado/core/utils/loader.py has big change,for example, miss some necessary modules ,e.g loader.DiscoverMode.DEFAULT, which is needed by avocado-vt.
```
Failed to load plugin from module "avocado_vt.plugins.vt_list_guests": ImportError("cannot import name 'loader' from 'avocado.core' (/usr/local/lib/python3.10/site-packages/avocado/core/__init__.py)") :
  File "/usr/local/lib/python3.10/site-packages/avocado/core/extension_manager.py", line 94, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/cirrus-ci-build/avocado_vt/plugins/vt_list_guests.py", line 6, in <module>
    from ..loader import guest_listing
  File "/tmp/cirrus-ci-build/avocado_vt/loader.py", line 23, in <module>
    from avocado.core import loader
```

**Comment by chunfuwen** [comment]
@clebergnu please help have a look

@luckyh
@dzhengfy 
@smitterl 
@Yingshun

**Comment by dzhengfy** [comment]
When debugging this issue, I also notice there is an avocado crash at the end of bootstrap report, so I am fixing it by https://github.com/avocado-framework/avocado-vt/pull/3590. 
With 3590, bootstrap can pass, but avocado list still fails with  `from avocado.core import loader` missing error (see above). @clebergnu  Here it seems a big changes in latest master branch under avocado.core folder. Could you give any advisement?  How to proceed for avocado-vt travis CI with latest avocado master test?

**Comment by clebergnu** [comment]
Hi everyone,

There was no *rename* of the `avocado.core.loader` module, but actually it's removal.  This has been planned for a long time, as the loader is really part of the legacy runner.

The `avocado_vt/loader.py` contains a bit of a mixed bag, and I'm working on a patch to remove the references to `avocado.core.loader`, while preserving the current functionality (`vt-list-guests` and `vt-list-archs`).

Please bear with me a bit longer and I'll follow up with a PR.

**Comment by chunfuwen** [comment]
@clebergnu  thank you for your efforts on this issue follows-up
