### ISSUE TITLE
Testcase for Nested vm

### ISSUE THREAD

**Issue by nguoido** [avocado-framework/avocado-vt#3657]
I would like to ask the does avocado-vt have already test about nested vm?

**Comment by PaulYuuu** [comment]
I think VT has a weak capability to run nested vm: https://github.com/avocado-framework/avocado-vt/blob/a99eb31e18fb4b837aeb01e67aaf875a99c69d25/virttest/env_process.py#L217

So I never use this, but maintain an ansible-playbook instead, to bootstrap the VT environment and then run test cases inside guest. the ansible test is in tp-qemu: https://github.com/autotest/tp-qemu/blob/master/qemu/tests/cfg/ansible_test.cfg

**Comment by nguoido** [comment]
Thanks @PaulYuuu i will try it
