### ISSUE TITLE
Avocado PyPI deployment pipeline

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado-vt#3834]
Hi all,

I wanted to update some pip requirements of our plugin today as
```diff
----------------------------- requirements_pip.txt -----------------------------
index 7bb5744e..ddf80591 100644
@@ -1,12 +1,12 @@
 coverage
 codecov
 
 simplejson==3.8.0
 netaddr>=0.7.18
 netifaces>=0.10.5
 
 aexpect==1.7.0
-avocado-framework==98.0
-avocado-framework-plugin-vt==98.0
+avocado-framework==103.0
+avocado-framework-plugin-vt==103.0
 
 graphviz==0.14.1
 ```
 but then the following error
 ```
 ERROR: Could not find a version that satisfies the requirement avocado-framework-plugin-vt==103.0 (from versions: 57.4, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 98.0)
ERROR: No matching distribution found for avocado-framework-plugin-vt==103.0
 ```
 made me recall that there was an arrangement to not release Avocado VT any longer and for tagging to simply provide useful information on compatibility.

However, considering that such PyPI package was provided in the past and we already have some infrastructure in place for it, should we at least enable it for LTS or some releases? Something like this would be a very useful deployment method for any potential newcomers and my usual workflows involve testing this anyway.

@luckyh @clebergnu @richtja Any thoughts?

**Comment by pevogam** [comment]
I now noticed that there are both a tag and a PyPI package for the 104.0 release but not for the LTS 103.0 release. @clebergnu Could we retroactively release a PyPI package for the 103.0 release since this is what our project explicitly depends on (`avocado-framework-plugin-vt==103.0` rather than `avocado-framework-plugin-vt>=103.0` for obvious reason considering the sometimes incompatible changes that come with newer non-LTS tags)? I think it is much more important to have the PyPI package for the LTS rather than follow up (and overall less tested) versions like 104.0 and onwards if we really have to choose.

**Comment by pevogam** [comment]
Hi @richtja and @luckyh , I keep getting this problem:
```
Collecting avocado-framework==103.0 (from -r requirements_pip.txt (line 9))
  Downloading avocado_framework-103.0-py3-none-any.whl.metadata (11 kB)
ERROR: Could not find a version that satisfies the requirement avocado-framework-plugin-vt==103.0 (from versions: 57.4, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 98.0, 104.0)
ERROR: No matching distribution found for avocado-framework-plugin-vt==103.0
```
When do you think it will be possible to have a PyPI release? As this is an LTS release it is much more important to have the correct package rather than 104.0 and onward.

**Comment by clebergnu** [comment]
Hi @pevogam,

There's no "Long Term Stability" (LTS) for Avocado-VT, but, we could/should have packages for all tags.  Would pushing a 103.0 package based on that tag solve your issue?

Thanks.

**Comment by pevogam** [comment]
> Hi @pevogam,
> 
> There's no "Long Term Stability" (LTS) for Avocado-VT, but, we could/should have packages for all tags. Would pushing a 103.0 package based on that tag solve your issue?
> 

While I am aware of the lack of backpropped fixes we all already tested Avocado for full compatibility with Avocado VT at the time of adding the tags so I don't see why we can't also release Avocado VT on PyPI as was done for 104.0. So yes, as our own plugin follows official releases and depends on Avocado VT this would really help.

**Comment by clebergnu** [comment]
> > Hi @pevogam,
> > There's no "Long Term Stability" (LTS) for Avocado-VT, but, we could/should have packages for all tags. Would pushing a 103.0 package based on that tag solve your issue?
> 
> While I am aware of the lack of backpropped fixes we all already tested Avocado for full compatibility with Avocado VT at the time of adding the tags so I don't see why we can't also release Avocado VT on PyPI as was done for 104.0. So yes, as our own plugin follows official releases and depends on Avocado VT this would really help.

103.0 is up on PyPI: https://pypi.org/project/avocado-framework-plugin-vt/103.0/

As a side note, the building and publishing of packages is not (yet) part of an automated release job in Avocado-VT as it is in Avocado, but it's definitely a welcome improvement.

**Comment by pevogam** [comment]
> As a side note, the building and publishing of packages is not (yet) part of an automated release job in Avocado-VT as it is in Avocado, but it's definitely a welcome improvement.

I assume we need a maintainer to help out with the automation of the pipeline, I was thinking of suggesting the same thing.
