### ISSUE TITLE
Install dependencies in `run_autotest`

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado-vt#444]
The `virttest.utils_test.run_autotest` should use package manager to check for `patch` and `gcc` as it might not be present on the image.

**Comment by xutian** [comment]
s/instal/install

**Comment by ldoktor** [comment]
Thanks, corrected. Btw I don't really have time to work on this, so anybody feel free to go ahead and implement it. (it should be relatively quick)

**Comment by ldoktor** [comment]
Would be nice but I don't really need this anymore...
