### ISSUE TITLE
 Broken dependency on nmap-ncat for RHEL/EPEL 6

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado-vt#45]
# yum install yum install avocado-plugins-vt
Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Install Process
Package yum-3.2.29-69.el6.noarch already installed and latest version
No package install available.
Resolving Dependencies
--> Running transaction check
---> Package avocado-plugins-vt.noarch 0:0.27.0-1.el6 will be installed
--> Processing Dependency: autotest-framework for package: avocado-plugins-vt-0.27.0-1.el6.noarch
--> Processing Dependency: nmap-ncat for package: avocado-plugins-vt-0.27.0-1.el6.noarch
--> Running transaction check
---> Package autotest-framework.noarch 0:0.16.0-2.el6 will be installed
---> Package avocado-plugins-vt.noarch 0:0.27.0-1.el6 will be installed
--> Processing Dependency: nmap-ncat for package: avocado-plugins-vt-0.27.0-1.el6.noarch
--> Finished Dependency Resolution
Error: Package: avocado-plugins-vt-0.27.0-1.el6.noarch (lmr-Autotest)
           Requires: nmap-ncat
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@astepano2 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 6.7 (Santiago)

**Comment by Andrei-Stepanov** [comment]
https://apps.fedoraproject.org/packages/nmap

**Comment by lmr** [comment]
OK,

**Comment by lmr** [comment]
That's my fault. `nmap-ncat` is only available for newer fedora. I'm going to fix the spec file to take that into account.

**Comment by lmr** [comment]
I just sent an updated version of avocado-plugins-vt to COPR to be built
https://copr.fedoraproject.org/coprs/lmr/Autotest/build/107093/
This version will require nmap instead of nmap-ncat.

When the build is ready, please let me know if it solves your issue (it should, but you never know). If it does, I'll close this issue.

**Comment by lmr** [comment]
This problem was fixed in 08f00b9d323e6007c97b3c43f1265b292494b61b

**Comment by lmr** [comment]
I'm closing this issue due to the fix committed as 08f00b9d323e6007c97b3c43f1265b292494b61b.
