### ISSUE TITLE
Lack of paramiko in reqs

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado-vt#46]
I have run:

pip install -r avocado/requirements.txt
pip install -r avocado-vt/requirements.txt

After that I got:

[root@astepano2 avocado]# ./scripts/avocado vt-bootstrap --vt-type qemu
Error loading avocado.core.plugins.virt_test_list -> EnvironmentError Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/fabric/network.py", line 24, in <module>
    import paramiko as ssh
ImportError: No module named paramiko

**Comment by Andrei-Stepanov** [comment]
By the way: yum install avocado-plugins-vt - does not require: python-paramiko.noarch as well.

**Comment by lmr** [comment]
`fabric` should be the responsible for pulling out `paramiko`...

**Comment by lmr** [comment]
Now, there's a point that, strictly speaking, `avocado-plugins-vt` should have an explicit dependency in `fabric`, but that's debatable since `avocado-plugins-vt` depends on `avocado`, that on its turn depends on `fabric`. 

Maybe (?) there's a bug in fabric that is not pulling out paramiko as it should? I'm going to check the paramiko setup.py file.

**Comment by lmr** [comment]
if sys.version_info[:2] < (2, 6):
            install_requires=['paramiko>=1.10,<1.13']
        else:
            install_requires=['paramiko>=1.10']

Nope, fabric's setup.py is fine. I don't know what happened in your system, but it didn't behave the way one would expect.

**Comment by lmr** [comment]
After investigating this, I believe this is a non issue (all relevant packages and requirement files do require fabric, which does require paramiko). I'm closing it.
