### ISSUE TITLE
Installlation failed on source base avocado.

### ISSUE THREAD

**Issue by kanssty** [avocado-framework/avocado-vt#498]
Hi,
Followed the guide of
http://avocado-framework.readthedocs.io/en/latest/ContributionGuide.html#hacking-and-using-avocado
I have installed avocado-vt on source base avocado as below.

[root@zs95kv2 avocado]# cd /avocado/
[root@zs95kv2 avocado]# git clone https://github.com/avocado-framework/avocado-vt.git
Cloning into 'avocado-vt'...
remote: Counting objects: 38364, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 38364 (delta 9), reused 0 (delta 0), pack-reused 38337
Receiving objects: 100% (38364/38364), 18.89 MiB | 7.02 MiB/s, done.
Resolving deltas: 100% (27198/27198), done.
[root@zs95kv2 avocado]# ll
total 12
drwxr-xr-x. 15 root root 4096 May 10 20:21 avocado
drwxr-xr-x. 14 root root 4096 May 10 20:57 avocado-vt
-rw-r--r--. 1 root root 118 May 10 20:32 sleeptest.yaml
[root@zs95kv2 avocado]# cd avocado
[root@zs95kv2 avocado]# avocado -v
Avocado 35.0
[root@zs95kv2 avocado]#

[root@zs95kv2 avocado]# make link
/usr/bin/python setup.py develop --user
running develop
running egg_info
writing avocado.egg-info/PKG-INFO
writing top-level names to avocado.egg-info/top_level.txt
writing dependency_links to avocado.egg-info/dependency_links.txt
writing entry points to avocado.egg-info/entry_points.txt
reading manifest file 'avocado.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'avocado.egg-info/SOURCES.txt'
running build_ext
Creating /root/.local/lib/python2.7/site-packages/avocado.egg-link (link to .)
Adding avocado 35.0 to easy-install.pth file
Installing avocado script to /root/.local/bin
Installing avocado-rest-client script to /root/.local/bin

Installed /avocado/avocado
Processing dependencies for avocado==35.0
Finished processing dependencies for avocado==35.0
for MAKEFILE in ../sleeptest.yaml ../avocado-vt;\
        do AVOCADO_DIRNAME=avocado make -C $MAKEFILE link &>/dev/null && echo ">> LINK $MAKEFILE" || echo ">> SKIP $MAKEFILE";\
done
>> SKIP ../sleeptest.yaml
>> LINK ../avocado-vt
[root@zs95kv2 avocado]#

But after installation. Avocado became not workable as below.

[root@zs95kv2 avocado]# avocado
Traceback (most recent call last):
  File "/usr/bin/avocado", line 5, in <module>
    pkg_resources.run_script('avocado==35.0', 'avocado')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1449, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'avocado'
[root@zs95kv2 avocado]#

Could you help me to take a look for this problem?

**Comment by kanssty** [comment]
I saw there are some env parameter on doc as below.

$ cd $AVOCADO_PROJECTS_DIR
$ git clone $AVOCADO_GIT
$ git clone $AVOCADO_PROJECT2
$ # Add more projects
$ cd avocado    # go into the main avocado project dir
$ make link

Where can I found these env parameter definition?

**Comment by PandaWei** [comment]
@kanssty 
Maybe you can try it again as the steps @ldoktor show us.
http://www.redhat.com/archives/avocado-devel/2016-April/msg00051.html

**Comment by PandaWei** [comment]
@kanssty 
Maybe you can try it again as the steps @ldoktor show us.
http://www.redhat.com/archives/avocado-devel/2016-April/msg00051.html

**Comment by PandaWei** [comment]
and remember to pull the latest master to fix the following,

logging.getLogger("avocado.app").error("Importing Loader, not CLoader")
NameError: name 'logging' is not defined
make: *** [develop] Error 1

**Comment by kanssty** [comment]
Hi, I removed old one and followed the reference try gain. But got the same result.


1 Remove old one
[root@zs95kv2 avocado]# make clean
/usr/bin/python setup.py clean
running clean
make -f /avocado/avocado/debian/rules clean || true
make[1]: Entering directory `/avocado/avocado'
make[1]: /avocado/avocado/debian/rules: No such file or directory
make[1]: *** No rule to make target `/avocado/avocado/debian/rules'.  Stop.
make[1]: Leaving directory `/avocado/avocado'
rm -rf build/ MANIFEST BUILD BUILDROOT SPECS RPMS SRPMS SOURCES
rm -f man/avocado.1
rm -f man/avocado-rest-client.1
rm -rf docs/build
find docs/source/api/ -name '*.rst' -delete
for MAKEFILE in ../sleeptest.yaml ../avocado-vt;\
        do AVOCADO_DIRNAME=avocado make -C $MAKEFILE unlink &>/dev/null && echo ">> UNLINK $MAKEFILE" || echo ">> SKIP $MAKEFILE";\
done
>> SKIP ../sleeptest.yaml
>> UNLINK ../avocado-vt
/usr/bin/python setup.py develop --uninstall --user
running develop
Removing /root/.local/lib/python2.7/site-packages/avocado.egg-link (link to .)
Removing avocado 35.0 from easy-install.pth file
Note: you must uninstall or replace scripts manually!
rm -rf avocado.egg-info
rm -rf /var/tmp/avocado*
rm -rf /tmp/avocado*
find . -name '*.pyc' -delete
[root@zs95kv2 avocado]# ll

And try again.

1)[root@zs95kv2 avocado]# git clone git://github.com/avocado-framework/avocado.git
Cloning into 'avocado'...
remote: Counting objects: 15898, done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 15898 (delta 41), reused 0 (delta 0), pack-reused 15813
Receiving objects: 100% (15898/15898), 8.36 MiB | 0 bytes/s, done.
Resolving deltas: 100% (10449/10449), done.
[root@zs95kv2 avocado]# cd avocado
2)[root@zs95kv2 avocado]# sudo make requirements
pip install "pip>=6.0.1"
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): pip>=6.0.1 in /usr/lib/python2.7/site-packages
pip install -r requirements.txt
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Ignoring stevedore: markers "python_version < '2.7'" don't match your environment
Ignoring argparse: markers "python_version < '2.7'" don't match your environment
Ignoring logutils: markers "python_version < '2.7'" don't match your environment
Ignoring importlib: markers "python_version < '2.7'" don't match your environment
Ignoring unittest2: markers "python_version < '2.7'" don't match your environment
Requirement already satisfied (use --upgrade to upgrade): fabric>=1.11.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.11 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): libvirt-python>=1.2.9 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyliblzma>=0.5.3 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pystache>=0.5.3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): requests>=1.2.3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): stevedore>=1.8.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): paramiko<2.0,>=1.10 in /usr/lib/python2.7/site-packages (from fabric>=1.11.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pbr>=1.6 in /usr/lib/python2.7/site-packages (from stevedore>=1.8.0->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/lib/python2.7/site-packages (from stevedore>=1.8.0->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.11 in /usr/lib/python2.7/site-packages (from paramiko<2.0,>=1.10->fabric>=1.11.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pycrypto!=2.4,>=2.1 in /usr/lib64/python2.7/site-packages (from paramiko<2.0,>=1.10->fabric>=1.11.0->-r requirements.txt (line 1))
[root@zs95kv2 avocado]#

3)[root@zs95kv2 avocado]# sudo python setup.py install
...................

copying avocado.egg-info/PKG-INFO -> build/bdist.linux-s390x/egg/EGG-INFO
copying avocado.egg-info/SOURCES.txt -> build/bdist.linux-s390x/egg/EGG-INFO
copying avocado.egg-info/dependency_links.txt -> build/bdist.linux-s390x/egg/EGG-INFO
copying avocado.egg-info/entry_points.txt -> build/bdist.linux-s390x/egg/EGG-INFO
copying avocado.egg-info/not-zip-safe -> build/bdist.linux-s390x/egg/EGG-INFO
copying avocado.egg-info/top_level.txt -> build/bdist.linux-s390x/egg/EGG-INFO
creating dist
creating 'dist/avocado-35.0-py2.7.egg' and adding 'build/bdist.linux-s390x/egg' to it
removing 'build/bdist.linux-s390x/egg' (and everything under it)
Processing avocado-35.0-py2.7.egg
removing '/usr/lib/python2.7/site-packages/avocado-35.0-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/avocado-35.0-py2.7.egg
Extracting avocado-35.0-py2.7.egg to /usr/lib/python2.7/site-packages
avocado 35.0 is already the active version in easy-install.pth
Installing avocado script to /usr/bin
Installing avocado-rest-client script to /usr/bin

Installed /usr/lib/python2.7/site-packages/avocado-35.0-py2.7.egg
Processing dependencies for avocado==35.0
Finished processing dependencies for avocado==35.0
[root@zs95kv2 avocado]#
[root@zs95kv2 avocado]#



4)[root@zs95kv2 avocado]# git clone https://github.com/avocado-framework/avocado-vt.git
Cloning into 'avocado-vt'...
remote: Counting objects: 38370, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 38370 (delta 13), reused 0 (delta 0), pack-reused 38337
Receiving objects: 100% (38370/38370), 18.89 MiB | 5.98 MiB/s, done.
Resolving deltas: 100% (27202/27202), done.
[root@zs95kv2 avocado]# ll
total 8
drwxr-xr-x. 15 root root 4096 May 11 04:44 avocado
drwxr-xr-x. 14 root root 4096 May 11 04:45 avocado-vt
[root@zs95kv2 avocado]#


5)[root@zs95kv2 avocado]# make link
/usr/bin/python setup.py develop --user
running develop
running egg_info
writing avocado.egg-info/PKG-INFO
writing top-level names to avocado.egg-info/top_level.txt
writing dependency_links to avocado.egg-info/dependency_links.txt
writing entry points to avocado.egg-info/entry_points.txt
reading manifest file 'avocado.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'avocado.egg-info/SOURCES.txt'
running build_ext
Creating /root/.local/lib/python2.7/site-packages/avocado.egg-link (link to .)
Adding avocado 35.0 to easy-install.pth file
Installing avocado script to /root/.local/bin
Installing avocado-rest-client script to /root/.local/bin

Installed /avocado/avocado
Processing dependencies for avocado==35.0
Finished processing dependencies for avocado==35.0
for MAKEFILE in ../avocado-vt;\
        do AVOCADO_DIRNAME=avocado make -C $MAKEFILE link &>/dev/null && echo ">> LINK $MAKEFILE" || echo ">> SKIP $MAKEFILE";\
done
>> LINK ../avocado-vt
[root@zs95kv2 avocado]#


6)[root@zs95kv2 avocado]# avocado
Traceback (most recent call last):
  File "/usr/bin/avocado", line 5, in <module>
    pkg_resources.run_script('avocado==35.0', 'avocado')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1449, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'avocado'
[root@zs95kv2 avocado]#


7)[root@zs95kv2 avocado]# ./scripts/avocado plugins
Failed to load plugin from module "avocado_vt.plugins.vt_list": ImportError('No module named aexpect',)
Failed to load plugin from module "avocado_vt.plugins.vt": ImportError('No module named aexpect',)
Plugins that add new commands (avocado.plugins.cli.cmd):
exec-path    Returns path to avocado bash libraries and exits.
run          Run one or more tests (native test, test alias, binary or script)
config       Shows avocado config keys
list         List available tests
multiplex    Generate a list of dictionaries with params from a multiplex file
plugins      Displays plugin information
distro       Shows detected Linux distribution
sysinfo      Collect system information
vt-bootstrap Avocado VT - implements the 'vt-bootstrap' subcommand
Plugins that add new options to commands (avocado.plugins.cli):
html    HTML job report options for 'run' subcommand
gdb     GDB options for the 'run' subcommand
xunit   xUnit output options
replay  Replay options for 'run' subcommand
json    JSON output options for 'run' command
vm      Virtual Machine options for 'run' subcommand
wrapper Implements the '--wrapper' flag for the 'run' subcommand
remote  Remote machine options for 'run' subcommand
journal Journal options for the 'run' subcommand
Plugins that run before/after the execution of jobs (avocado.plugins.job.prepost):
jobscripts Runs scripts before/after the job is run
[root@zs95kv2 avocado]#

**Comment by kanssty** [comment]
For the step of 
18. ./scripts/avocado plugins
I got the different error, not sure whether continue to execute the remaining steps.

**Comment by PandaWei** [comment]
you should install the requirements of avocado-vt
pip -r requirements.txt

**Comment by PandaWei** [comment]
avocado-vt/requirements.txt

**Comment by kanssty** [comment]
Thanks for your information, I think that you mean using **pip install -r requirements.txt
**
[root@zs95kv2 avocado-vt]# pwd
/avocado/avocado-vt
[root@zs95kv2 avocado-vt]# pip install -r requirements.txt
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting autotest>=0.16.2 (from -r requirements.txt (line 1))
  Downloading autotest-0.16.2.tar.gz (4.4MB)
    100% |████████████████████████████████| 4.4MB 115kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-v_DRe7/autotest/setup.py", line 23, in <module>
        from sphinx.setup_command import BuildDoc
    ImportError: No module named sphinx.setup_command

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v_DRe7/autotest

I got this error. My environment is Linux like zKVM system, not sure whether I can get this package.

**Comment by kanssty** [comment]
Reference this issue, got the resolve

https://github.com/autotest/autotest/issues/1006

[root@zs95kv2 avocado-vt]# pip install sphinx
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting sphinx
  Downloading Sphinx-1.4.1-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 315kB/s
Collecting babel!=2.0,>=1.3 (from sphinx)
  Downloading Babel-2.3.4-py2.py3-none-any.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 71kB/s
Collecting snowballstemmer>=1.1 (from sphinx)
  Downloading snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 65kB 7.4MB/s
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python2.7/site-packages (from sphinx)
Collecting Pygments>=2.0 (from sphinx)
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
    100% |████████████████████████████████| 757kB 662kB/s
Collecting docutils>=0.11 (from sphinx)
  Downloading docutils-0.12.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 315kB/s
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in /usr/lib/python2.7/site-packages (from sphinx)
Collecting imagesize (from sphinx)
  Downloading imagesize-0.7.1-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx)
  Downloading alabaster-0.7.8-py2.py3-none-any.whl
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx)
  Downloading pytz-2016.4-py2.py3-none-any.whl (480kB)
    100% |████████████████████████████████| 483kB 1.1MB/s
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib64/python2.7/site-packages (from Jinja2>=2.3->sphinx)
Installing collected packages: pytz, babel, snowballstemmer, Pygments, docutils, imagesize, alabaster, sphinx
  Found existing installation: pytz 2012d
    DEPRECATION: Uninstalling a distutils installed project (pytz) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pytz-2012d:
      Successfully uninstalled pytz-2012d
  Found existing installation: Babel 0.9.6
    Uninstalling Babel-0.9.6:
      Successfully uninstalled Babel-0.9.6
  Found existing installation: Pygments 1.4
    Uninstalling Pygments-1.4:
      Successfully uninstalled Pygments-1.4
  Running setup.py install for docutils
Successfully installed Pygments-2.1.3 alabaster-0.7.8 babel-2.3.4 docutils-0.12 imagesize-0.7.1 pytz-2016.4 snowballstemmer-1.2.1 sphinx-1.4.1
[root@zs95kv2 avocado-vt]# pip install -r requirements.txt
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting autotest>=0.16.2 (from -r requirements.txt (line 1))
  Using cached autotest-0.16.2.tar.gz
Collecting aexpect>=1.0.0 (from -r requirements.txt (line 2))
  Downloading aexpect-1.1.0.tar.gz
Collecting simplejson>=3.5.3 (from -r requirements.txt (line 3))
  Downloading simplejson-3.8.2.tar.gz (76kB)
    100% |████████████████████████████████| 77kB 3.9MB/s
Installing collected packages: autotest, aexpect, simplejson
  Running setup.py install for autotest
  Running setup.py install for aexpect
  Running setup.py install for simplejson
Successfully installed aexpect-1.1.0 autotest-0.16.2 simplejson-3.8.2
[root@zs95kv2 avocado-vt]#

**Comment by PandaWei** [comment]
OK, I guess "scripts/avocado plugins" works well, right?

**Comment by kanssty** [comment]
Yes, I saw the error message, should I need to install p7zip here? I will figure it by myself.
Thank you very much.

But I have another little question, why command of "avocado" is not workable after avocado-vt installation? Should we use scripts/avocado to specify the all path here?

root@zs95kv2 avocado]# make link
/usr/bin/python setup.py develop --user
running develop
running egg_info
writing avocado.egg-info/PKG-INFO
writing top-level names to avocado.egg-info/top_level.txt
writing dependency_links to avocado.egg-info/dependency_links.txt
writing entry points to avocado.egg-info/entry_points.txt
reading manifest file 'avocado.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'avocado.egg-info/SOURCES.txt'
running build_ext
Creating /root/.local/lib/python2.7/site-packages/avocado.egg-link (link to .)
avocado 35.0 is already the active version in easy-install.pth
Installing avocado script to /root/.local/bin
Installing avocado-rest-client script to /root/.local/bin

Installed /avocado/avocado
Processing dependencies for avocado==35.0
Finished processing dependencies for avocado==35.0
for MAKEFILE in ../avocado-vt;\
        do AVOCADO_DIRNAME=avocado make -C $MAKEFILE link &>/dev/null && echo ">> LINK $MAKEFILE" || echo ">> SKIP $MAKEFILE";\
done
>> LINK ../avocado-vt

[root@zs95kv2 avocado]# avocado
Traceback (most recent call last):
  File "/usr/bin/avocado", line 5, in <module>
    pkg_resources.run_script('avocado==35.0', 'avocado')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1449, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'avocado'


[root@zs95kv2 avocado]# scripts/avocado plugins
Failed to load plugin from module "avocado_vt.plugins.vt_list": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this messag
Failed to load plugin from module "avocado_vt.plugins.vt": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
Plugins that add new commands (avocado.plugins.cli.cmd):
plugins      Displays plugin information
multiplex    Generate a list of dictionaries with params from a multiplex file
list         List available tests
config       Shows avocado config keys
run          Run one or more tests (native test, test alias, binary or script)
exec-path    Returns path to avocado bash libraries and exits.
sysinfo      Collect system information
vt-bootstrap Avocado VT - implements the 'vt-bootstrap' subcommand
distro       Shows detected Linux distribution
Plugins that add new options to commands (avocado.plugins.cli):
gdb     GDB options for the 'run' subcommand
vm      Virtual Machine options for 'run' subcommand
wrapper Implements the '--wrapper' flag for the 'run' subcommand
json    JSON output options for 'run' command
journal Journal options for the 'run' subcommand
remote  Remote machine options for 'run' subcommand
xunit   xUnit output options
replay  Replay options for 'run' subcommand
html    HTML job report options for 'run' subcommand
Plugins that run before/after the execution of jobs (avocado.plugins.job.prepost):
jobscripts Runs scripts before/after the job is run
[root@zs95kv2 avocado]#


[root@zs95kv2 avocado]# ./scripts/avocado vt-bootstrap
Failed to load plugin from module "avocado_vt.plugins.vt_list": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
Failed to load plugin from module "avocado_vt.plugins.vt": EnvironmentError("Bootstrap missing. Execute 'avocado vt-bootstrap' or disable this plugin to get rid of this message",)
05:38:05 INFO | qemu test config helper
05:38:05 INFO |
05:38:05 INFO | 1 - Checking the mandatory programs and headers
05:38:05 ERROR| Required command 7za is missing. You must install it
05:38:05 INFO | /sbin/tcpdump OK
05:38:05 INFO | /bin/nc OK
05:38:05 INFO | /sbin/ip OK
05:38:05 INFO | /sbin/arping OK
05:38:05 INFO | /bin/gcc OK
05:38:05 INFO | /usr/include/asm-generic/unistd.h OK
05:38:05 INFO | /usr/include/asm-generic/types.h OK
05:38:05 INFO | /usr/include/asm-generic/socket.h OK
05:38:05 INFO | /usr/include/python2.7/Python.h OK
05:38:05 INFO | Missing (cmds/includes): 7za
05:38:05 INFO | Install the missing programs and/or headers and re-run boostrap
[root@zs95kv2 avocado]#

**Comment by PandaWei** [comment]
Generally speaking，
We can directly run "avocado" after installation. 
I don‘t know why you met errors...
I guess you install/uninstall avocado several times, which broken the environment.

PS, I hope you  enjoy avocado and avocado-vt.

**Comment by kanssty** [comment]
OK, Done. Thank you very much.

**Comment by ldoktor** [comment]
@kanssty glad to hear that. One note regarding 7za, it's not really mandatory. It's only required for running JeOS, which is prebuilt minimized version of Fedora compressed in 7z. It's only built for x86_64.

If you want to avoid the 7za check and speedup the bootstrap by avoiding downloading and uncompressing the JeOS, you can use `--vt-guest-os ` followed by the guest os without an asset file (I'm using `RHEL.7.devel`).
