### ISSUE TITLE
Remove duplicate

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado-vt#54]
# grep vt_config avocado/core/plugins/virt_test_bootstrap.py
        args.vt_config = None
        args.vt_config = None

It is in the same function, one assignment above the another

**Comment by lmr** [comment]
Sent a fix on https://github.com/avocado-framework/avocado-vt/pull/55

**Comment by lmr** [comment]
Merged, I'm closing this. Thanks @Andrei-Stepanov !
