### ISSUE TITLE
problem in case of avocado vt-bootstrap --vt-type libvirt  

### ISSUE THREAD

**Issue by svirt** [avocado-framework/avocado-vt#56]
Hello,
I installed avocado/avocado-vt according to the manual described here http://avocado-vt.readthedocs.org/en/latest/GetStartedGuide.html and wanted to try it with libvirt.
First I performed the bootstrap step as it's described: avocado vt-bootstrap --vt-type libvirt  
Then checked with avocado plugins -> no errors.
But when I wanted to list the tests I got the following error:
avocado list --verbose
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Test discovery plugin <avocado.core.plugins.virt_test.VirtTestLoader object at 0x7f1f3f8c5590> failed: 'include base.cfg' (/usr/share/avocado/data/avocado-vt/backends/qemu/cfg/tests-shared.cfg:13): file does not exist or it's not a regular file

looks like the config file is taken from the qemu dir and not from the libvirt one (and there is no base.cfg in qemu subdir, but there is one in libvirt subdir)

ls -la /usr/share/avocado/data/avocado-vt/backends/qemu/cfg/
total 16
drwxr-xr-x. 2 root root 4096 Aug  5 15:20 .
drwxr-xr-x. 3 root root 4096 Aug  5 15:03 ..
-rw-r--r--. 1 root root  373 Aug  4 03:58 tests.cfg
-rw-r--r--. 1 root root 1312 Aug  4 03:58 tests-shared.cfg

ls -la /usr/share/avocado/data/avocado-vt/backends/libvirt/cfg/
total 1304
drwxr-xr-x. 2 root root   4096 Aug  5 15:20 .
drwxr-xr-x. 3 root root   4096 Aug  5 15:03 ..
-rw-r--r--. 1 root root  17202 Aug  5 15:04 base.cfg
-rw-r--r--. 1 root root    526 Aug  5 15:04 cdkeys.cfg
-rw-r--r--. 1 root root   8472 Aug  4 03:58 default_tests
-rw-r--r--. 1 root root    329 Aug  4 03:58 drivers.cfg
-rw-r--r--. 1 root root  13303 Aug  5 15:04 guest-hw.cfg
-rw-r--r--. 1 root root 295070 Aug  5 15:52 guest-os.cfg
-rw-r--r--. 1 root root   1008 Aug  5 15:04 machines.cfg
-rw-r--r--. 1 root root 947043 Aug  5 15:52 subtests.cfg
-rw-r--r--. 1 root root    688 Aug  4 03:58 tests.cfg
-rw-r--r--. 1 root root    989 Aug  4 03:58 tests-shared.cfg
-rw-r--r--. 1 root root   7595 Aug  5 15:04 virtio-win.cfg

Looks like I don't do anything wrong in the steps above, so probably it's an issue related to libvirt type in avocado?

Thank you

**Comment by sathnaga** [comment]
looks like it is expecting bootstrap of qemu by default, try doing below
avocado vt-bootstrap --vt-type qemu
Check if you can get rid of this error, in anycase, I guess this is issue to be looked at.
@lmr @adereis 

am using avocado version 27 and able to list the tests using the same
$ avocado --version
Avocado 0.27.0
$avocado list --verbose
....
.....
ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
BUGGY: 0
FILTERED: 0
INSTRUMENTED: 52
MISSING: 0
NOT_A_TEST: 30
SIMPLE: 1
VT: 1907

**Comment by svirt** [comment]
Yes, I tried it also with --vt-type qemu and it was working without errors. The error occurs with --vt-type libvirt case

Thanks

**Comment by lmr** [comment]
@svirt I can't reproduce the error you're having, my setup goes on just fine.

**Comment by lmr** [comment]
And lists tests just fine as well

**Comment by lmr** [comment]
OK, I found a way to reproduce it. Hang on.

**Comment by lmr** [comment]
Apparently this happens when we have an inconsistency of state between the files in ~/avocado/data/avocado-vt/backends dir. After removing that dir and re-running setup, everything starts to work fine. Now I'm going to see if I can make things more foolproof.

**Comment by lmr** [comment]
OK @svirt, I have sent a PR to fix the problem and will be soon pushed to master. Meanwhile, you have a workaround: Delete `~/avocado/data/avocado-vt/backends` [1] and re-run bootstrap. That should do it.

My fix is going to the next avocado-vt version, due next Thursday, Aug 13th. The fix basically only ensures you don't have to delete that dir first before re-running bootstrap.

[1] This of course assumes that you are using the default data dir settings.

**Comment by svirt** [comment]
*@lmr*
Hello , thank you for your feedback, I will try the workaround

**Comment by svirt** [comment]
**@lmr**
Hello , I tried the workaround and as I have avocado installed by rpms, then the directory you mentioned should be */usr/share/avocado/data/avocado-vt/backends* ,right?  So I deleted it and re-ran the bootstrap with *avocado vt-bootstrap --vt-type libvirt* but still got the same error... and just in  ~/avocado itself I have only this:

ls -la ~/avocado
total 12
drwxr-xr-x.  3 root root 4096 Apr 23 09:55 .
dr-xr-x---. 25 root root 4096 Aug  5 15:20 ..
drwxr-xr-x. 26 root root 4096 Aug  5 14:11 job-results


Thank you

**Comment by lmr** [comment]
No, I actually forgot that libvirt tests mandate root. In this case, instead of `~/avocado`, it should be `/var/lib/avocado`, making it `/var/lib/avocado/data/avocado-vt/backends` dir.

You've deleted the wrong dir, and now you'll have to re-install the rpms.

**Comment by svirt** [comment]
I will try that in my environment

**Comment by svirt** [comment]
in my case there is no such directory  /var/lib/avocado  at all... maybe because of rpm-install case?
