### ISSUE TITLE
Enh req: `avocado plugins' doesn't work out of avocado's dir

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado-vt#61]
git clone avocado
git clone avocado-vt

export PATH="$PATH:/root/avocado/scripts"

cd anywhere .....

And here is a bug:

# avocado plugins

Unloadable plugin modules:
    avocado.core.plugins.virt_test            OSError [Errno 2] No such file or directory: '/avocado-vt/test-providers.d'
    avocado.core.plugins.virt_test_bootstrap  OSError [Errno 2] No such file or directory: '/avocado-vt/test-providers.d'
    avocado.core.plugins.virt_test_list       OSError [Errno 2] No such file or directory: '/avocado-vt/test-providers.d'

# cd avocado
make link

cd anywhere .....

Still doesn't work:

# avocado plugins
Error loading avocado.core.plugins.virt_test_bootstrap -> OSError [Errno 2] No such file or directory: '/avocado-vt/backends'
Error loading avocado.core.plugins.virt_test_list -> OSError [Errno 2] No such file or directory: '/avocado-vt/backends'
Error loading avocado.core.plugins.virt_test -> OSError [Errno 2] No such file or directory: '/avocado-vt/backends'

**Comment by lmr** [comment]
Why would it have to work outside of the avocado dir?

**Comment by lmr** [comment]
`make link` will link the virttest dir on top of the avocado dir, and that is necessary for you to run the code. It was never meant to be used outside the top avocado repo. I guess if you do want to do that, you'd have to export the avocado-vt dir to the `PYTHONPATH`, but again, I never tried it or have the interest of trying.

If you want to have something that works outside the directories, you are much better served by doing

    make build-rpm-all
    rpm -ivh RPMS/avocado*.rpm

In avocado and avocado-vt repos, in sequence. i'm closing this issue.
