### ISSUE TITLE
mount issue in the nfs.py

### ISSUE THREAD

**Issue by svirt** [avocado-framework/avocado-vt#685]
Looks like there is an issue at line 330

`        mount_cmd = ssh_cmd + "'mount -t nfs %s %s -o %s'" % (self.mount_src,
                                                              self.mount_dir,
                                                              self.mount_options)`

when  self.mount_options is None then the mount command fails as -o does not get any argument. I would suggest to add a check for self.mount_options if it's empty or not , then based on it to use -o option or not. If this approach is fine then I can send a patch

**Comment by sathnaga** [comment]
@svirt yep, looks good

**Comment by will-Do** [comment]
Yes, split 'mount_options' to a new line should be good
