### ISSUE TITLE
Latest avocado-vt plugin installs still shows 39.0 version 

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado-vt#695]
Steps to reproduce:
$git clone https://github.com/avocado-framework/avocado-vt.git avocado-vt-upstream
$cd avocado-vt-upstream
$ git log -1 --stat
commit 5a72e9d9c5c0f0c72f02811f6c7ba342d3db47c0
Author: Cleber Rosa <crosa@redhat.com>
Date:   Mon Sep 12 17:17:19 2016 -0300

    Release 41.0
    
    Signed-off-by: Cleber Rosa <crosa@redhat.com>

 Makefile                | 2 +-
 avocado-plugins-vt.spec | 7 +++++--
 docs/source/conf.py     | 4 ++--
 3 files changed, 8 insertions(+), 5 deletions(-)

$python setup.py install
...
...
Installed /usr/lib/python2.7/site-packages/avocado_plugins_vt-39.0-py2.7.egg
Processing dependencies for avocado-plugins-vt==39.0
Finished processing dependencies for avocado-plugins-vt==39.0-------------------NOK

**Comment by sathnaga** [comment]
@clebergnu @ldoktor

**Comment by sathnaga** [comment]
Looks like the setup.py still has 39.0 version
setup.py:21:VERSION = '39.0'

**Comment by sathnaga** [comment]
Send a fixup: https://github.com/avocado-framework/avocado-vt/pull/696

**Comment by sathnaga** [comment]
Installed /usr/lib/python2.7/site-packages/avocado_plugins_vt-41.0-py2.7.egg
Processing dependencies for avocado-plugins-vt==41.0
Finished processing dependencies for avocado-plugins-vt==41.0

**Comment by ldoktor** [comment]
Thank you, patch merged.
