### ISSUE TITLE
Unfriendly message when virt-test not initialized

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado-vt#7]
When bootstrap in virt-test is not runned, `avocado list` finishes with exception `file ... not found`, `avocado plugins` shows no exception and `avocado run boot` reports no matching tests.

I'm sorry for not reporting the actual message, I had to search for a while to identify the problem and it got lost. 

Steps:

1. git clone autotest, virt-test, avocado and avocado-vt
2. cd avocado && make link
3. ./scripts/avocado list

After running `./run --bootstrap` in virt-test it started to work fine. What is confusing is the message of `avocado list` (it shouldn't fail and simply skip the plugin) and it'd be nice to detect uninitialized virt-test and report it in `avocado plugins` (IMO simple query for non-empty `VIRTTEST_DIR/backends` or `VIRTTEST_DIR/test-providers/download/` is enough)

**Comment by lmr** [comment]
OK, fair enough.

**Comment by ldoktor** [comment]
Cannot access 'vt_list_all': File not found

**Comment by ldoktor** [comment]
fixed by https://github.com/avocado-framework/avocado-vt/pull/10
