### ISSUE TITLE
Broken Travis-CI

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado-vt#760]
The Travis-CI check is broken due to updated pylint. The fix is quite straight forward, but due to number of files it will take some time so let's use this issue to track the progress.

I can do the fixing as I already fixed the `avocado`, but I have another pressing matter right now. I can start working on it in about 2 hours, so if anyone wants to step up and do the fixing in the mean time, feel free to assign yourself and work on it, otherwise I'll assign myself when I start.

@xutian @will-Do @PandaWei @Hao-Liu @Andrei-Stepanov @clebergnu @apahim

**Comment by ldoktor** [comment]
OK, no volunteers, let me take care of it...

**Comment by Andrei-Stepanov** [comment]
Thank you!

**Comment by will-Do** [comment]
Sorry missed this issue in the weekend, thank you @ldoktor

**Comment by ldoktor** [comment]
No problem, note that I haven't looked at tp-* so there still might be some issues there...
