### ISSUE TITLE
session.close() doesn't work

### ISSUE THREAD

**Issue by suqinhuang** [avocado-framework/avocado-vt#792]
the session fd is increasing during test, if test is repeated in loop e.g balloon_hotplug, will cause error:
"filedescriptor out of range in select()"

**Comment by xutian** [comment]
we can't close FD opened in output_function (utils_misc.log_line)

**Comment by xutian** [comment]
@ldoktor  any idea about this issue?

**Comment by ldoktor** [comment]
Hello @xutian, nice debugging job 😉. Well I don't understand why the `log_line` needs to keep all the log files opened, I'd just use:

```python
with open(..., "aw") as log:
    log.write(...)
```

which would append the output at the end of the file and close the file handler afterwards.

Anyway if you want to keep the list of opened files, then I'd recommend either going through it during manual cleanup, or at least developing a class which would handle the `log_line` and would use `__del__` to close them automatically (but not always).

**Comment by ldoktor** [comment]
PS: Based on the usage the manual cleanup looks like the best approach. I'd still recommend creating a class to encapsulate the locks, list-of-opened-files, etc. Then I'd instantiate it in `utils_misc` and kept the `log_line` function to point to the instance's `log_line` method.

**Comment by xutian** [comment]
has fixed, let's close this PR.
