### ISSUE TITLE
docs: broken links

### ISSUE THREAD

**Issue by rdkdd** [avocado-framework/avocado-vt#885]
Links for [setuptools](https://pythonhosted.org/setuptools) and [entry-points](https://pythonhosted.org/setuptools/pkg_resources.html#entry-points)
are broken in avocado-vt documentation: [Plugin system](http://avocado-framework.readthedocs.io/en/46.0/Plugins.html).

**Comment by xutian** [comment]
@apahim  checked this link, looks it's a issue for avocado-framework/avocado documentation, can you look at it.

**Comment by rdkdd** [comment]
@xutian  ok I corrected it. https://github.com/avocado-framework/avocado/pull/1854
