### ISSUE TITLE
Failed to load plugin from module "avocado_vt.plugins.vt_list": ImportError('No module named simplejson',)

### ISSUE THREAD

**Issue by nvgoldin** [avocado-framework/avocado-vt#888]
Followed the docs - http://avocado-vt.readthedocs.io/en/latest/GetStartedGuide.html, on a fresh el7.3 installation, and after installing the RPM:
```bash
[root@vm-el73 ~]# avocado vt-bootstrap --vt-type qemu
Failed to load plugin from module "avocado_vt.plugins.vt_list": ImportError('No module named simplejson',)
Failed to load plugin from module "avocado_vt.plugins.vt": ImportError('No module named simplejson',)
Failed to load plugin from module "avocado_vt.plugins.vt_bootstrap": ImportError('No module named simplejson',)
```
Installing ``python2-simplejson`` manually resolved the issue.

**Comment by xutian** [comment]
@nvgoldin  please use pip to installed all requirements before setup avocado-vt and avocado-framework.

sudo pip install -r requirements.txt

**Comment by nvgoldin** [comment]
Hi @xutian,
But I installed it from the RPM. I see it is requring simplejson for el6, but not el7.

**Comment by xutian** [comment]
@nvgoldin  thanks your report this issue, fix(https://github.com/avocado-framework/avocado-vt/pull/924) has submit

**Comment by xutian** [comment]
PR merged, please try next released packages
