### ISSUE TITLE
Automem breaks unattended_install

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado-vt#971]
The commit 683ac015a5dde931842979e079609cd63656459d which moved the automem outside the vm handling breaks `unattended_install` as the params set in env_preprocess are not propagated back to params.

Anyway the big question is whether we want to have this by default as (if I understand it correctly) it breaks all tests with multiple machines, therefor I think it should be an optional feature only enabled when asked for and the evaluation should happen when started.

Another issue I have with this is that it (probably) breaks the `keep_guest_running` as it changes the memory size... (I haven't checked that)

```
avocado --show all run unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads --vt-machine-type q35 --vt-guest-os RHEL.7.devel
...
avocado.test: Reproduced traceback from: /home/medic/Work/Projekty/avocado/avocado/avocado/core/test.py:570
avocado.test: Traceback (most recent call last):
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/avocado_vt/test.py", line 225, in setUp
avocado.test:     self._runTest()
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/avocado_vt/test.py", line 366, in _runTest
avocado.test:     run_func(self, params, env)
avocado.test:   File "/home/medic/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/unattended_install.py", line 14, in run
avocado.test:     unattended_install.run(test, params, env)
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/virttest/error_context.py", line 135, in new_fn
avocado.test:     return fn(*args, **kwargs)
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/virttest/tests/unattended_install.py", line 1219, in run
avocado.test:     vm.create(params=params)
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/virttest/error_context.py", line 135, in new_fn
avocado.test:     return fn(*args, **kwargs)
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/virttest/qemu_vm.py", line 2695, in create
avocado.test:     self.devices = self.make_create_command()
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/virttest/qemu_vm.py", line 1825, in make_create_command
avocado.test:     add_memorys(devices, params)
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/virttest/qemu_vm.py", line 908, in add_memorys
avocado.test:     max_usable_mem_m = int(mem_params["max_usable_mem"])
avocado.test:   File "/home/medic/Work/Projekty/avocado/avocado-vt/virttest/utils_params.py", line 25, in __getitem__
avocado.test:     key)
avocado.test: ParamNotFound: Mandatory parameter 'max_usable_mem' is missing. Check your cfg files for typos/mistakes
avocado.test: 
avocado.test: SKIP 1-io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads -> TestSkipError: Mandatory parameter 'max_usable_mem' is missing. Check your cfg files for typos/mistakes
avocado.test: 
```

**Comment by ldoktor** [comment]
@xutian you introduced the change, can you please take a look at this? I'll eventually get to this, but right now I need to focus on something else. In my CI I used `--vt-extra-params automem=no` as a workaround, but I believe this should be fixed properly...

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG: avocado_vt: automem breaks unattended_install](https://trello.com/c/u1UWPjwT/984-bug-avocado-vt-automem-breaks-unattended-install)

**Comment by xutian** [comment]
sorry for that, will fix it ASAP

**Comment by ldoktor** [comment]
No problem, btw how about the concerns I mentioned? Are they valid? I only looked at this briefly, found a workaround and described it here....

1. Does it work with tests spawning multiple machines?
2. Is it automatically turned off when running migration tests (as you claim it does not work with them)
3. Does it work properly with `keep_guest_running` (I mean are VMs preserved, or always recreated due to few MB difference in memory?)

**Comment by xutian** [comment]
@ldoktor 

1. I think it works on multiple machines.
2.  Yes,  I have a patch to in tp-qemu to disable automem for migration related tests. https://github.com/autotest/tp-qemu/pull/933
3.  No,  if guest free memory less than VM requried memory, else I think it works.

agree with your, let me disable it by default.

Thanks,
Xu

**Comment by xutian** [comment]
@ldoktor  sent two hotfix, can you help to review it.
https://github.com/avocado-framework/avocado-vt/pull/972

thanks,
Xu

**Comment by ldoktor** [comment]
OK, I looked at it a bit more thoroughly and the (1) is indeed fine, the (2) should actually be also fine, unless the machine run outs of memory, right? And the (3) should also not be affected, so it could even stay as default... Sorry for not looking at it thoroughly before reporting this (anyway the issue is still on, but your fix looks promising)

**Comment by xutian** [comment]
close as bug has fixed.
